### ISSUE TITLE
Error when use "rpmbuild -bb syslog-ng.spec"

### ISSUE THREAD

**Issue by malidong** [balabit/syslog-ng#1029]
Hello,

I got the error message below when build a rpm package by "rpmbuild -bb syslog-ng.spec" on CentOS 7 64bit.
Could someone helps?

thanks.
MA
********************************\* log************************************************
running build
running build_py
running install
running install_lib
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    packages=['syslogng', 'syslogng.debuggercli'])
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 101, in run
    self.byte_compile(outfiles)
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 138, in byte_compile
    dry_run=self.dry_run)
  File "/usr/lib64/python2.7/distutils/util.py", line 469, in byte_compile
    % (file, prefix))
ValueError: invalid prefix: filename '/lib/python2.7/site-packages/syslogng/**init**.py' doesn't start with '/root/rpmbuild/BUILDROOT/syslog-ng-3.7.3-1.x86_64'
********************************\* log************************************************

**Comment by czanik** [comment]
Which spec file do you use? The one bundled in the syslog-ng release tgz is not actively maintained, as it's not possible to support all the different rpm-based distributions with a single spec file.

My rpm packaging for Fedora & CentOS 7 is available at https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng37/ You can either use the pre-built packages, or use the source rpm and modify the spec file from there to your needs.

**Comment by malidong** [comment]
Hi czanik,

Thanks for your reply.
Yes, I used spec file in the syslog-ng release tgz file and thanks for your rpm packaging.
If I want to compile and packaging syslog-ng to rpm, could you tell me witch spec file should I use?

MA

**Comment by faxm0dem** [comment]
use one of the SRPMs from @czanik's Link on copr

**Comment by MrAnno** [comment]
Closing this ticket due to inactivity.

The question has been answered.
You can also have a look at our Docker-based build environment in which you can create an RPM:
https://github.com/balabit/syslog-ng/tree/master/dbld/images/centos7
