### ISSUE TITLE
core dump after upgrading 3.7.2 to 3.7.3

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1156]
Hi,

Using @czanik's epel7 packages, and after upgrading 3.7.2 to 3.7.3 I get one to two core dumps per day on our production servers (~1k messages per second). Sometimes the crash seems related to java, sometimes not. Here's a few entries from `/var/log/messages` for different crashes:

crash 1:

```
ERROR:lib/logmsg.c:503:log_msg_set_value: assertion failed: (!log_msg_is_write_protected(self))
```

crash 2:

```
# A fatal error has been detected by the Java Runtime Environment:
```

crash 3:

```
Invalid database*** Error in `/usr/sbin/syslog-ng': malloc(): memory corruption: 0x0000000002186471 ***
```

crash 4:

```
*** Error in `/usr/sbin/syslog-ng': malloc(): smallbin double linked list corrupted: 0x00007f143442ab70 ***
```

strangely enough, the contents of the log always contain mixed in occurences from GeoIp `invalid database`.

I have core dumps for crashes 1 and 2. Both mention patterndb:

```
#0  0x00007fcdfc9775f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install GeoIP-1.5.0-9.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.163-3.el7.x86_64 elfutils-libs-0.163-3.el7.x86_64 eventlog-0.2.13-4.el7.x86_64 gmp-6.0.0-12.el7_1.x86_64 gnutls-3.3.8-14.el7_2.x86_64 ivykis-0.36.2-2.el7.x86_64 java-1.8.0-openjdk-headless-1.8.0.101-3.b13.el7_2.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libattr-2.4.46-12.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libesmtp-1.0.6-7.el7.x86_64 libffi-3.0.13-16.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libgcrypt-1.5.3-12.el7_1.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libtasn1-3.8-2.el7.x86_64 nettle-2.7.1-4.el7.x86_64 p11-kit-0.20.7-3.el7.x86_64 protobuf-c-1.0.2-2.el7.x86_64 python-libs-2.7.5-34.el7.x86_64 riemann-c-client-1.6.1-4.el7.x86_64 syslog-ng-incubator-0.5.0-0.el7.x86_64 trousers-0.3.13-1.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt full
#0  0x00007fcdfc9775f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 22138
        selftid = 21402
#1  0x00007fcdfc978ce8 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {140517228654960, 140522483455660, 140522714497632, 140517228655248,
              140522683071472, 140522686505984, 140522683028610, 12911248, 140522476788099, 8, 1, 0, 140522683540765, 0, 140522686511632, 0}},
          sa_flags = -1216350464, sa_restorer = 0x8}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fcdf04ec429 in os::abort(bool) () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#3  0x00007fcdf068b796 in VMError::report_and_die() () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#4  0x00007fcdf04f55c7 in JVM_handle_linux_signal () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#5  0x00007fcdf04e9848 in signalHandler(int, siginfo_t*, void*) () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre/lib/amd64/server/libjvm.so
No symbol table info available.
#6  <signal handler called>
No locals.
#7  nv_table_make_direct (handle=639, entry=0x7fcdd0e0a578, user_data=<optimized out>) at lib/nvtable.c:348
        self = 0x7fcce804e2f0
        ref_handle = 3
#8  0x00007fcdfe53cb5a in nv_table_foreach_entry (self=self@entry=0x7fcce804e2f0, func=func@entry=0x7fcdfe53cf70 <nv_table_make_direct>,
    user_data=user_data@entry=0x7fccb77fba40) at lib/nvtable.c:603
        dyn_entries = <optimized out>
        entry = <optimized out>
        i = 11
#9  0x00007fcdfe53ce98 in nv_table_add_value (self=0x7fcce804e2f0, handle=handle@entry=3, name=name@entry=0x9ca1e0 "MESSAGE", name_len=<optimized out>,
    value=value@entry=0x7fcce805e360 "patterndb: session ended for aligrid.6759:909@[::134.158.173.64] after 0:01:11", value_len=value_len@entry=78,
    new_entry=new_entry@entry=0x7fccb77fbabc) at lib/nvtable.c:390
        data = {0x7fcce804e2f0, 0x3}
        ofs = <optimized out>
        dyn_slot = 0x0
#10 0x00007fcdfe52fb07 in log_msg_set_value (self=self@entry=0x7fcceb03a700, handle=3,
    value=value@entry=0x7fcce805e360 "patterndb: session ended for aligrid.6759:909@[::134.158.173.64] after 0:01:11", value_len=value_len@entry=78)
    at lib/logmsg.c:522
        name = 0x9ca1e0 "MESSAGE"
        name_len = 7
        new_entry = 0
        __func__ = "log_msg_set_value"
#11 0x00007fcdf82c1b34 in log_msg_set_value_by_name (length=<optimized out>,
    value=0x7fcce805e360 "patterndb: session ended for aligrid.6759:909@[::134.158.173.64] after 0:01:11", name=<optimized out>, self=0x7fcceb03a700)
    at lib/logmsg.h:259
        handle = <optimized out>
#12 synthetic_message_apply (self=self@entry=0xb9df68, context=context@entry=0x7fccac536c00, msg=msg@entry=0x7fcceb03a700, buffer=buffer@entry=0x7fcce80e3f40)
    at modules/dbparser/synthetic-message.c:79
        i = 0
#13 0x00007fcdf82c1ca1 in synthetic_message_generate_with_context (self=0xb9df68, inherit_mode=<optimized out>, context=context@entry=0x7fccac536c00,
---Type <return> to continue, or q <return> to quit---
    buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/synthetic-message.c:164
        __func__ = "synthetic_message_generate_with_context"
#14 0x00007fcdf82be947 in pdb_generate_message (self=<optimized out>, context=context@entry=0x7fccac536c00, msg=msg@entry=0x7fcce8346180,
    buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/patterndb.c:257
No locals.
#15 0x00007fcdf82be977 in pdb_execute_action_message (self=<optimized out>, db=db@entry=0xb0c4b0, context=context@entry=0x7fccac536c00, msg=msg@entry=0x7fcce8346180,
    buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/patterndb.c:267
        genmsg = <optimized out>
#16 0x00007fcdf82be9ba in pdb_execute_action (self=<optimized out>, db=db@entry=0xb0c4b0, rule=rule@entry=0xb94ea0, context=context@entry=0x7fccac536c00,
    msg=msg@entry=0x7fcce8346180, buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/patterndb.c:280
        __func__ = "pdb_execute_action"
#17 0x00007fcdf82bea55 in pdb_trigger_action (self=<optimized out>, db=db@entry=0xb0c4b0, rule=rule@entry=0xb94ea0, trigger=trigger@entry=RAT_MATCH,
    context=context@entry=0x7fccac536c00, msg=msg@entry=0x7fcce8346180, buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/patterndb.c:292
No locals.
#18 0x00007fcdf82beab9 in pdb_run_rule_actions (self=self@entry=0xb94ea0, db=db@entry=0xb0c4b0, trigger=trigger@entry=RAT_MATCH,
    context=context@entry=0x7fccac536c00, msg=msg@entry=0x7fcce8346180, buffer=buffer@entry=0x7fcce80e3f40) at modules/dbparser/patterndb.c:306
        action = <optimized out>
        i = 0
#19 0x00007fcdf82bf4bd in _pattern_db_process (self=0xb0c4b0, lookup=lookup@entry=0x7fccb77fbcb0, dbg_list=dbg_list@entry=0x0) at modules/dbparser/patterndb.c:673
        context = 0x7fccac536c00
        buffer = 0x7fcce80e3f40
        rule = 0xb94ea0
        msg = 0x7fcce8346180
#20 0x00007fcdf82bf82b in pattern_db_process (self=<optimized out>, msg=<optimized out>) at modules/dbparser/patterndb.c:710
        lookup = {msg = 0x7fcce8346180, program_handle = 4, message_handle = 3, message_string = 0xeae5e380 <Address 0xeae5e380 out of bounds>, message_len = 0}
#21 0x00007fcdf82baca0 in log_db_parser_process (s=0xa16d20, pmsg=0x7fccb77fbd38, path_options=0x7fccb77fbe50,
    input=0x7fccabf7bee5 " aligrid.6759:909@[::134.158.173.64] disc 0:01:11", input_len=49) at modules/dbparser/dbparser.c:213
        self = 0xa16d20
#22 0x00007fcdfe558ac2 in log_parser_queue (s=0xa16d20, msg=0x7fcce8346180, path_options=0x7fccb77fbe50, user_data=<optimized out>) at lib/parser/parser-expr.c:62
        payload = 0x7fccabf7b690
        value_len = 49
        self = 0xa16d20
        success = <optimized out>
#23 0x00007fcdfe52eb07 in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#24 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#25 log_pipe_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=0x7fccb77fbe50) at lib/logpipe.h:341
No locals.
#26 0x00007fcdfe52f22f in log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#27 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#28 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#29 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=0xae8650) at lib/logpipe.h:341
No locals.
#30 log_multiplexer_queue (s=0xae84f0, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/logmpx.c:106
        next_hop = 0xae8650
---Type <return> to continue, or q <return> to quit---
        self = 0xae84f0
        i = 1
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x7fccb77fbe4c}
        matched = 1
        delivered = 0
        last_delivery = <optimized out>
        fallback = <optimized out>
#31 0x00007fcdfe52eb07 in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#32 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#33 log_pipe_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=0x7fccb77fbfa0) at lib/logpipe.h:341
No locals.
#34 0x00007fcdfe52f22f in log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#35 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#36 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#37 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=0x9fc920) at lib/logpipe.h:341
No locals.
#38 log_multiplexer_queue (s=0x9fc980, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/logmpx.c:106
        next_hop = 0x9fc920
        self = 0x9fc980
        i = 0
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x7fccb77fbf9c}
        matched = 1
        delivered = 0
        last_delivery = <optimized out>
        fallback = <optimized out>
#39 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#40 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#41 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
No locals.
#42 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#43 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#44 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#45 log_rewrite_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/rewrite/rewrite-expr.c:62
        length = 1142269796802422272
#46 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#47 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#48 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
---Type <return> to continue, or q <return> to quit---
No locals.
#49 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#50 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#51 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#52 log_rewrite_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/rewrite/rewrite-expr.c:62
        length = 140518056773856
#53 0x00007fcdfe558a4c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#54 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#55 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#56 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#57 log_parser_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/parser/parser-expr.c:80
        self = <optimized out>
        success = <optimized out>
#58 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#59 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#60 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
No locals.
#61 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#39 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#40 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#41 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
No locals.
#42 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#43 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#44 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#45 log_rewrite_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/rewrite/rewrite-expr.c:62
        length = 1142269796802422272
#46 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#47 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#48 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
---Type <return> to continue, or q <return> to quit---
No locals.
#49 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#50 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#51 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#52 log_rewrite_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/rewrite/rewrite-expr.c:62
        length = 140518056773856
#53 0x00007fcdfe558a4c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#54 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#55 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#56 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#57 log_parser_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/parser/parser-expr.c:80
        self = <optimized out>
        success = <optimized out>
#58 0x00007fcdfe55aa3c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#59 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#60 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
No locals.
#61 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#62 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#63 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#64 log_rewrite_queue (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/rewrite/rewrite-expr.c:62
        length = 140522711893516
#65 0x00007fcdfe5297c8 in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#66 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#67 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#68 log_pipe_forward_msg (msg=msg@entry=0x7fcce8346180, path_options=path_options@entry=0x7fccb77fc410, self=0x9fa5d0) at lib/logpipe.h:299
No locals.
#69 0x00007fcdfe529e4c in log_pipe_queue (path_options=0x7fccb77fc410, msg=0x7fcce8346180, s=0x9fa5d0) at lib/logpipe.h:341
No locals.
#70 log_pipe_forward_msg (self=0x9fa5d0, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#71 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#72 log_pipe_forward_msg (self=0x9fa5d0, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
---Type <return> to continue, or q <return> to quit---
No locals.
#73 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#74 log_pipe_forward_msg (self=0x9fa5d0, path_options=<optimized out>, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#75 log_src_driver_queue_method (s=<optimized out>, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/driver.c:170
        self = <optimized out>
        cfg = <optimized out>
#76 0x00007fcdfe53494c in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#77 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#78 log_pipe_queue (path_options=0x7fccb77fc410, msg=0x7fcce8346180, s=<optimized out>) at lib/logpipe.h:341
No locals.
#79 log_pipe_forward_msg (self=<optimized out>, path_options=0x7fccb77fc410, msg=0x7fcce8346180) at lib/logpipe.h:299
No locals.
#80 log_source_queue (s=0xb0b700, msg=0x7fcce8346180, path_options=<optimized out>, user_data=<optimized out>) at lib/logsource.c:307
        self = 0xb0b700
        i = <optimized out>
        __func__ = "log_source_queue"
#81 0x00007fcdfe534ec8 in log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:337
No locals.
#82 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#83 log_pipe_queue (path_options=<optimized out>, msg=<optimized out>, s=<optimized out>) at lib/logpipe.h:341
No locals.
#84 log_pipe_forward_msg (self=<optimized out>, path_options=<optimized out>, msg=<optimized out>) at lib/logpipe.h:299
No locals.
#85 log_pipe_queue (path_options=<optimized out>, msg=0x7fcce8346180, s=0xb0b700) at lib/logpipe.h:341
No locals.
#86 log_source_post (self=self@entry=0xb0b700, msg=msg@entry=0x7fcce8346180) at lib/logsource.c:240
        path_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
        old_window_size = <optimized out>
        __func__ = "log_source_post"
#87 0x00007fcdfe533729 in log_reader_handle_line (aux=0x7fccb77fc4c0, length=<optimized out>, line=<optimized out>, self=0xb0b700) at lib/logreader.c:319
        m = 0x7fcce8346180
#88 log_reader_fetch_log (self=self@entry=0xb0b700) at lib/logreader.c:380
        bookmark = <optimized out>
        msg = 0x7fcd08003000 "{\"xrootd\":{\"svc\":\"XrootdXeq\",\"someid\":\"22575\"},\"timestamp\":\"2016-08-04T16:32:47+02:00\",\"tags\":\"xrootd,.source.s_xrd_alicet2\",\"smurf\":{\"usage\":\"xrootd\",\"usag\":\"xrootd\",\"status\":\"Up\",\"rack\":\"osservice3\""...
        msg_len = 594
        status = <optimized out>
        msg_count = 1
        may_read = 1
        aux = {peer_addr = 0x7fcce8dba760,
          data = "..."  <repeats 42 times>..., end_ptr = 0}
        __func__ = "log_reader_fetch_log"
#89 0x00007fcdfe533849 in log_reader_work_perform (s=0xb0b700) at lib/logreader.c:86
        self = 0xb0b700
#90 0x00007fcdfe53b25d in _work (self=<optimized out>) at lib/mainloop-io-worker.c:52
No locals.
#91 0x00007fcdfcf24c67 in iv_work_thread_do_work () from /lib64/libivykis.so.0
No symbol table info available.
#92 0x00007fcdfcf23fc3 in iv_run_tasks () from /lib64/libivykis.so.0
No symbol table info available.
#93 0x00007fcdfcf267dc in iv_main () from /lib64/libivykis.so.0
No symbol table info available.
#94 0x00007fcdfcf24ab4 in iv_work_thread () from /lib64/libivykis.so.0
No symbol table info available.
#95 0x00007fcdfcf27270 in iv_thread_handler () from /lib64/libivykis.so.0
No symbol table info available.
#96 0x00007fcdfcd0bdc5 in start_thread (arg=0x7fccb77ff700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x7fccb77ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140517228672768, 6649451074050460090, 0, 140517228673472, 140517228672768, 43, -6638597796576491078,
                -6639324939125782086}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#97 0x00007fcdfca38ced in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

I'm not familiar with core analysis, but both stack traces mention a message matching the same patterndb rule. This rule does not use any geoip teplate function, but some other rules do.

I apologize for the vague nature of this bugreport.
I'll make a few tests, one including removing the seemingly involved patterndb rule.

**Comment by lbudai** [comment]
@faxm0dem : I think the geoip issue is resolved by this: https://github.com/balabit/syslog-ng/commit/490ac4f3fad6c3921eb9d614ef9031fad9098dc6

**Comment by faxm0dem** [comment]
I removed the rule, now the crash happens with another message in the stack.
I'm not a gdb guru, could you shed some light on my trace? @lbudai do you imply the crash is due to geoip?

**Comment by MrAnno** [comment]
This issue seems to be outdated. Please reopen if you experience any of the 4 crashes using the latest version.
