### ISSUE TITLE
loggen crashes when using tls

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1182]
reproduction:
start syslog-ng with the config below (keys does not need)
start loggen:
loggen --inet --rate=1000000 --size=200 --interval=30 --active-connections=10 --quiet --use-ssl 169.254.1.21 514

result:
** Error in `/opt/syslog-ng/bin/loggen': double free or corruption (fasttop): 0x00007f86080010c0 ***
*** Error in `/opt/syslog-ng/bin/loggen': double free or corruption (fasttop): 0x00007f85f8001690 ***
*** Error in `/opt/syslog-ng/bin/loggen': double free or corruption (!prev): 0x00007f860c001360 ***

gdb:
(gdb) bt
#0  0x00007f559ee6cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f559ee70028 in __GI_abort () at abort.c:89
#2  0x00007f559eea92a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f559efb76b0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f559eeb555e in malloc_printerr (ptr=<optimized out>, str=0x7f559efb7878 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007f559f982f8d in CRYPTO_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007f559f985891 in OBJ_NAME_add () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007f559fd40fb1 in SSL_library_init () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#8  0x0000000000403e76 in ?? ()
#9  0x0000000000402d3a in active_thread ()
#10 0x00007f559f486f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f559f203184 in start_thread (arg=0x7f55a015b700) at pthread_create.c:312
#12 0x00007f559ef3037d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

root@test20:~# syslog-ng -V
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 3.8.1-1

(3.7 is also affected)
-----
syslog-ng config:
root@test21:/opt/syslog-ng# cat etc/syslog-ng.conf 
@version: 3.8
options {
    keep_hostname(no);
    threaded(yes);
    stats_level(2);
    use_dns(no);
};
source s_network_fa30d29831b34992ab2ef3396f4d2eb2 {
    network(ip(0.0.0.0)
 log_fetch_limit(1000)
 log_iw_size(10000)
 max_connections(10)
 port(514)
 tls(peer_verify(optional-untrusted) cert_file("/var/testdb_working_dir/7532e934-fb97-49dc-8f2b-2169f0952a9a.txt") key_file("/var/testdb_working_dir/d185686d-a039-4ece-bd7b-522733f00d10.txt"))
 transport("tls"));
};
destination d_file_622fb85dc0f4431bb3107d388dabb713 {
    file("/var/testdb_working_dir/cb108da5-0ab7-4221-b48a-6d225f17a8c2" flush_lines(1000)
 log_fifo_size(20000));
};
log {
source(s_network_fa30d29831b34992ab2ef3396f4d2eb2);
destination(d_file_622fb85dc0f4431bb3107d388dabb713);

flags(flow-control);
};

**Comment by MrAnno** [comment]
Root cause:
OpenSSL is not automatically thread-safe.
"OpenSSL uses a number of global data structures that will be implicitly shared whenever multiple threads use OpenSSL."

We need to use mutexes with [this API](https://www.openssl.org/docs/man1.0.2/crypto/threads.html).

**Comment by pzoleex** [comment]
I tried it, the fix works
