### ISSUE TITLE
java-based destinations: Give understandable error message if class not found

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1188]
it is related to https://github.com/balabit/syslog-ng/issues/1187.

If client-lib-dir() is not configured properly, for example the destination specific jar files are missing, syslog-ng displays only the next message:
```
[2016-09-01T10:45:53.190640] Add path to classpath: /home/pzolee/projects/syslog-ng-ose/install/lib/syslog-ng/java-modules/syslog-ng-core.jar;
[2016-09-01T10:45:53.193655] Error initializing message pipeline;
```

This is not really informative and makes the debugging very hard.

Instead, it should displays an error message about class not found and list the classes.
Similar to this:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/Elasticsearch
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.Elasticsearch
```

**Comment by bkil-syslogng** [comment]
Duplicates #1044

**Comment by bobrik** [comment]
I was getting the same cryptic error:

```
[2017-08-16T00:18:53.308117] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
```

All because in my tests I did not pass all variables to config renderer and it produced:

```
kafka(
  # ...
  kafka-bootstrap-servers()
  # ...
);
```

**Comment by furiel** [comment]
After https://github.com/balabit/syslog-ng/pull/2478/commits/7353ea03b8a99ac858c813250dc3dfdac3b7306e,
syslog-ng writes the following exception:
```
[2019-02-08T10:09:06.809639] Exception: TestDestination;
java.lang.ClassNotFoundException: TestDestination
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:67)
[2019-02-08T10:09:06.811296] Can't find class; class_name='TestDestination'
[2019-02-08T10:09:06.811315] If you have reloaded syslog-ng, the JVM is not used anymore, but it is still running. If you want to stop JVM, stop syslog-ng and then start syslog-ng again;
[2019-02-08T10:09:06.811331] Error initializing message pipeline; plugin_name='java', location='../etc/java.conf:4:3'
```
@pzoleex does this fix your issue?

**Comment by furiel** [comment]
Closing with https://github.com/balabit/syslog-ng/commit/7353ea03b8a99ac858c813250dc3dfdac3b7306e:
