### ISSUE TITLE
Syslog-ng log destination Kafka: Can't find class

### ISSUE THREAD

**Issue by SergioFernandezStratio** [balabit/syslog-ng#1220]
Hi all,

I've trying to get working syslog-ng to write logs into Kafka over Centos7 without success. I've installed packages from [https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng38/packages/](https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng38/packages/) and followed instructions and prerrequisites from [https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-kafka.html](https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-kafka.html), but when I launch a log with the kafka defined destination, I get the following error:

```
[2016-10-03T14:16:06.952122] WARNING: Default value changed for the prefix() option of systemd-journal source in syslog-ng 3.8; old_value='', new_value='.journald.'
[2016-10-03T14:16:07.035539] Error: org/apache/kafka/clients/producer/Callback;
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/Callback
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:67)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.Callback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
[2016-10-03T14:16:07.036740] Can't find class; class_name='org.syslog_ng.kafka.KafkaDestination'
[2016-10-03T14:16:07.037093] Error initializing message pipeline
```
I've installed Kafka jars in /opt/kafka/libs. I've added a kafka.conf configuration file to syslog-ng with following content:

```
destination d_kafka {
  kafka(
    client-lib-dir("/usr/lib64/syslog-ng/java-modules/*.jar:/opt/kafka/libs/*.jar")
    kafka-bootstrap-servers("kafka1:9092,kafka2:9092")
    topic("${HOST}")
  );
};
#log { source(s_sys); filter(f_cron); destination(d_kafka); };
```

Problem appear when I uncomment last line (and it tries to write).

Can anyone help me?

**Comment by fekete-robert** [comment]
Hi, 

Try to set the client-lib-dir() without the *.jar, like: client-lib-dir("/usr/lib64/syslog-ng/java-modules/), this might be a doc bug.

**Comment by SergioFernandezStratio** [comment]
Hi, @fekete-robert 
That did the trick. Thank you very much!
