### ISSUE TITLE
csv-parser appears not to be thread safe when attached to a network source

### ISSUE THREAD

**Issue by cventers** [balabit/syslog-ng#1334]
## Version of syslog-ng

```
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: dbparser,afprog,cef,graphite,afsmtp,csvparser,disk-buffer,affile,confgen,linux-kmsg-format,cryptofuncs,syslogformat,json-plugin,afuser,afstomp,pseudofile,add-contextual-data,afsocket,basicfuncs,date,system-source,kvformat,riemann,curl
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

## Platform

Linux <redacted hostname> 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
CentOS release 6.8 (Final)

# Issue

## Failure

It seems that csv-parser does not work properly when attached to a network source and syslog-ng is running in threaded mode. This may be an unusual configuration, but it's one I've used quite successfully for many years and TBs of data from a 100+ node cluster under the 3.3 series.

The behavior under 3.8.1 is that the parser randomly fills the column macros with garbage and eventually segfaults (often because the current_column is being NULLed while another thread is trying to get its name).

If this is now an unsupported configuration, I recommend either a documentation warning or an assertion if threaded != no and the csv-parser is attached to a network source.

## Configuration

```
source s_feed {
    tcp(ip(IP REDACTED) port(1999) tls(
        key_file("KEY REDACTED")
        cert_file("CRT REDACTED")
        peer_verify(optional-trusted)
        ssl-options(no-sslv2, no-sslv3, no-tlsv1)
    ) max-connections(256) log-iw-size(25600));
};

parser p_hostsep {
    csv-parser(columns("IMSG.EPATH","IMSG.REMMSG")
        delimiters(" ")
        flags(drop-invalid,greedy,escape-none,strip-whitespace)
        quote-pairs("")
    );
};

log {
    source(s_feed);
    parser(p_hostsep);

    # ...
};

```

**Comment by mitzkia** [comment]
I could reproduce the crash, 

used configuration:
```
@version: 3.9
options {
	threaded(yes);
};
source s_feed {
    tcp(ip("127.0.0.1") port(1999) max-connections(256) log-iw-size(25600));
};
parser p_hostsep {
    csv-parser(columns("IMSG.EPATH","IMSG.REMMSG")
        delimiters(" ")
        flags(drop-invalid,greedy,escape-none,strip-whitespace)
        quote-pairs("")
    );
};
destination d_file {
	file("/tmp/output");
};
log {
    source(s_feed);
    parser(p_hostsep);
    destination(d_file);
};
```

trigger to crash syslog-ng: `bin/loggen -r 100 -I 100 -i 127.0.0.1 1999 --active-connections=10`

bt full:
[bt_full.txt](https://github.com/balabit/syslog-ng/files/788385/bt_full.txt)


bt:

```
Thread 5 "syslog-ng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3415700 (LWP 4043)]
0x00007ffff7b608fa in csv_scanner_get_current_name (self=0x5555557d96b8) at ../lib/scanner/csv-scanner/csv-scanner.c:378
378	  return (const gchar *) self->current_column->data;
(gdb) bt
#0  0x00007ffff7b608fa in csv_scanner_get_current_name (self=0x5555557d96b8) at ../lib/scanner/csv-scanner/csv-scanner.c:378
#1  0x00007ffff50431f1 in csv_parser_process (s=0x5555557d9600, pmsg=0x7ffff3412050, path_options=0x7ffff3412220, 
    input=0x7fffe800726d "seq: 0000000004, thread: 0000, runid: 1487619508, stamp: 2017-02-20T20:38:28 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD"..., input_len=205) at ../modules/csvparser/csvparser.c:124
#2  0x00007ffff7b6d601 in log_parser_process_message (self=0x5555557d9600, pmsg=0x7ffff3412050, path_options=0x7ffff3412220) at ../lib/parser/parser-expr.c:61
#3  0x00007ffff7b6d6e1 in log_parser_queue (s=0x5555557d9600, msg=0x7fffe8007070, path_options=0x7ffff3412220, user_data=0x0) at ../lib/parser/parser-expr.c:82
#4  0x00007ffff7b34f94 in log_pipe_queue (s=0x5555557d9600, msg=0x7fffe8007070, path_options=0x7ffff3412220) at ../lib/logpipe.h:339
#5  0x00007ffff7b34e30 in log_pipe_forward_msg (self=0x555555785e20, msg=0x7fffe8007070, path_options=0x7ffff3412220) at ../lib/logpipe.h:302
#6  0x00007ffff7b34fad in log_pipe_queue (s=0x555555785e20, msg=0x7fffe8007070, path_options=0x7ffff3412220) at ../lib/logpipe.h:343
#7  0x00007ffff7b34e30 in log_pipe_forward_msg (self=0x55555578cf10, msg=0x7fffe8007070, path_options=0x7ffff3412220) at ../lib/logpipe.h:302
#8  0x00007ffff7b34fad in log_pipe_queue (s=0x55555578cf10, msg=0x7fffe8007070, path_options=0x7ffff3412220) at ../lib/logpipe.h:343
#9  0x00007ffff7b35191 in log_multiplexer_queue (s=0x55555578cf80, msg=0x7fffe8007070, path_options=0x7ffff34125f0, user_data=0x0) at ../lib/logmpx.c:92
#10 0x00007ffff7b2d59f in log_pipe_queue (s=0x55555578cf80, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:339
#11 0x00007ffff7b2d43b in log_pipe_forward_msg (self=0x555555799c10, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:302
#12 0x00007ffff7b2d5b8 in log_pipe_queue (s=0x555555799c10, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:343
#13 0x00007ffff7b2d43b in log_pipe_forward_msg (self=0x555555799b80, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:302
#14 0x00007ffff7b2d5b8 in log_pipe_queue (s=0x555555799b80, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:343
#15 0x00007ffff7b2d43b in log_pipe_forward_msg (self=0x5555557d8da0, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:302
#16 0x00007ffff7b2dcba in log_src_driver_queue_method (s=0x5555557d8da0, msg=0x7fffe8007070, path_options=0x7ffff34125f0, user_data=0x0) at ../lib/driver.c:172
#17 0x00007ffff7b38dee in log_pipe_queue (s=0x5555557d8da0, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:339
#18 0x00007ffff7b38c8a in log_pipe_forward_msg (self=0x5555557b7490, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:302
#19 0x00007ffff7b38e07 in log_pipe_queue (s=0x5555557b7490, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:343
---Type <return> to continue, or q <return> to quit---
#20 0x00007ffff7b38c8a in log_pipe_forward_msg (self=0x5555557b7a30, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:302
#21 0x00007ffff7b39a2a in log_source_queue (s=0x5555557b7a30, msg=0x7fffe8007070, path_options=0x7ffff34125f0, user_data=0x0) at ../lib/logsource.c:323
#22 0x00007ffff7b38dee in log_pipe_queue (s=0x5555557b7a30, msg=0x7fffe8007070, path_options=0x7ffff34125f0) at ../lib/logpipe.h:339
#23 0x00007ffff7b396ec in log_source_post (self=0x5555557b7a30, msg=0x7fffe8007070) at ../lib/logsource.c:253
#24 0x00007ffff7b37dbc in log_reader_handle_line (self=0x5555557b7a30, 
    line=0x7fffe8003000 "<38>2017-02-20T20:38:28 localhost prg00000[1234]: seq: 0000000004, thread: 0000, runid: 1487619508, stamp: 2017-02-20T20:38:28 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDP"..., length=255, aux=0x7ffff34126a0) at ../lib/logreader.c:320
#25 0x00007ffff7b37f77 in log_reader_fetch_log (self=0x5555557b7a30) at ../lib/logreader.c:381
#26 0x00007ffff7b3772e in log_reader_work_perform (s=0x5555557b7a30) at ../lib/logreader.c:88
#27 0x00007ffff7b412e6 in _work (self=0x5555557b7bb0) at ../lib/mainloop-io-worker.c:52
#28 0x00007ffff7b8d90d in iv_work_thread_do_work (_thr=0x5555557bbff0) at ../../../../lib/ivykis/src/iv_work.c:118
#29 0x00007ffff7b8c801 in iv_run_tasks (st=0x7fffe80008c0) at ../../../../lib/ivykis/src/iv_task.c:48
#30 0x00007ffff7b8fb3a in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:106
#31 0x00007ffff7b8dc11 in iv_work_thread (_thr=0x5555557bbff0) at ../../../../lib/ivykis/src/iv_work.c:200
#32 0x00007ffff7b907b1 in iv_thread_handler (_thr=0x5555557bc0c0) at ../../../../lib/ivykis/src/iv_thread_posix.c:142
#33 0x00007ffff75cc6ca in start_thread (arg=0x7ffff3415700) at pthread_create.c:333
#34 0x00007ffff73060af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```
