### ISSUE TITLE
SigSegv: while stress testing syslog-ng (log_reader_handle_line, log_reader_fetch_log)

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#1502]
syslog-ng version:

builded from actual OSE master
latest git commit: 282ec7c
Reproduction:
1, Use the following (valid) syslog-ng config:
```
@version: 3.9

options {
    time_reopen(1);
    threaded(yes);
};

source s_network {
    network( ip("127.0.0.1") port(10001));
};

destination d_http {
    http(
        method(put)
        url("http://localhost:8080/")
        disk_buffer(disk-buf-size(1000000) reliable(no) dir("/tmp/"))
    );
};


log {
    source(s_network);
    destination(d_http);
};
```
2, start syslog-ng in a loop cycle:
```
while true ; do sbin/syslog-ng -Fedv --enable-core -f ~/micek_work/syslog_ng_configs/syslog_ng_http_3.conf ; done
```
3, send messages to syslog-ng in loop cycle:
```
while true ; do ./bin/loggen -s 8888 -r 1000 -i 127.0.0.1 10001 --active-connections=10 ; done
```
4, send HUP and STOP signal to syslog-ng in loop cycle:
```
while true ; do pkill -1 syslog-ng ; pkill -15 syslog-ng ; done
```

Generated backtrace:
```
Core was generated by `sbin/syslog-ng -Fedv --enable-core -f /home/micek/micek_work/syslog_ng_configs/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  malloc_consolidate (av=av@entry=0x7feee8000020) at malloc.c:4216
4216	malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7feeee521700 (LWP 24288))]
(gdb) bt full
#0  malloc_consolidate (av=av@entry=0x7feee8000020) at malloc.c:4216
        fb = 0x7feee8000028
        maxfb = 0x7feee8000070
        p = 0x7feee80026a0
        nextp = <optimized out>
        unsorted_bin = 0x7feee8000078
        first_unsorted = <optimized out>
        nextchunk = 0x7feee8002720
        size = 128
        nextsize = 2147483640
        prevsize = <optimized out>
        nextinuse = <error reading variable nextinuse (Cannot access memory at address 0x7fef68002720)>
        bck = <optimized out>
        fwd = <optimized out>
#1  0x00007feef82cfd1f in _int_malloc (av=av@entry=0x7feee8000020, bytes=bytes@entry=1024) at malloc.c:3485
        nb = 1040
        idx = 64
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        errstr = 0x0
        __func__ = "_int_malloc"
#2  0x00007feef82d1d84 in __GI___libc_malloc (bytes=bytes@entry=1024) at malloc.c:2925
        ar_ptr = 0x7feee8000020
        victim = <optimized out>
        hook = <optimized out>
#3  0x00007feef82d8b9a in __GI___strdup (
    s=0x7feeee51df80 "<38>2017-05-29T20:43:53 localhost prg00005[1234]: seq: 0000000001, thread: 0005, runid: 1496083433, stamp: 2017-05-29T20:43:53 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDP"...) at strdup.c:42
        len = 1024
        new = <optimized out>
#4  0x00007feef7a3a6fd in evt_tag_str () from /usr/lib/x86_64-linux-gnu/libevtlog.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#5  0x00007feef7a3a96c in evt_tag_printf () from /usr/lib/x86_64-linux-gnu/libevtlog.so.0
No symbol table info available.
#6  0x00007feef8bc9603 in log_reader_handle_line (self=0x5602611d1630, 
    line=0x7feee8006a10 "<38>2017-05-29T20:43:53 localhost prg00005[1234]: seq: 0000000001, thread: 0005, runid: 1496083433, stamp: 2017-05-29T20:43:53 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDP"..., length=8191, aux=0x7feeee51e4e0) at ../lib/logreader.c:309
        m = 0x560261166930
#7  0x00007feef8bc99de in log_reader_fetch_log (self=0x5602611d1630) at ../lib/logreader.c:381
        bookmark = 0x56026115fa28
        msg = 0x7feee8006a10 "<38>2017-05-29T20:43:53 localhost prg00005[1234]: seq: 0000000001, thread: 0005, runid: 1496083433, stamp: 2017-05-29T20:43:53 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDP"...
        msg_len = 8191
        status = LPS_SUCCESS
        msg_count = 2
        may_read = 1
        aux = {peer_addr = 0x0, data = '\000' <repeats 432 times>..., end_ptr = 0}
        __func__ = "log_reader_fetch_log"
#8  0x00007feef8bc8af2 in log_reader_work_perform (s=0x5602611d1630) at ../lib/logreader.c:88
        self = 0x5602611d1630
#9  0x00007feef8bda337 in _work (self=0x5602611d17b8) at ../lib/mainloop-io-worker.c:52
No locals.
#10 0x00007feef8c5c2f4 in iv_work_thread_do_work (_thr=0x560261166830) at ../../../../lib/ivykis/src/iv_work.c:118
        work = 0x5602611d17d8
        thr = 0x560261166830
        pool = 0x5602611590c0
        last_seq = 10
#11 0x00007feef8c5a636 in iv_run_tasks (st=0x7feee80008c0) at ../../../../lib/ivykis/src/iv_task.c:48
        t = 0x560261166878
        tasks = {next = 0x7feeee51e9d0, prev = 0x7feeee51e9d0}
#12 0x00007feef8c5fe2d in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:106
        to = {tv_sec = 140664177289776, tv_nsec = 0}
        st = 0x7feee80008c0
#13 0x00007feef8c5c85a in iv_work_thread (_thr=0x560261166830) at ../../../../lib/ivykis/src/iv_work.c:200
        thr = 0x560261166830
        pool = 0x5602611590c0
#14 0x00007feef8c6135e in iv_thread_handler (_thr=0x560261179b80) at ../../../../lib/ivykis/src/iv_thread_posix.c:142
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {0, 88349874181977386, 140721785223902, 140721785223903, 140664177301952, 140664177301248, 
                88349874144228650, 88326594631644458}, __mask_was_saved = 0}}, __pad = {0x7feeee51eb30, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x7feef8c611a0 <iv_thread_cleanup_handler>
        __cancel_arg = 0x560261179b80
---Type <return> to continue, or q <return> to quit---
        __not_first_call = 0
        thr = 0x560261179b80
#15 0x00007feef861a6da in start_thread (arg=0x7feeee521700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7feeee521700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140664177301248, -79871695322532566, 140721785223902, 140721785223903, 140664177301952, 140664177301248, 
                88349874188268842, 88328023384470826}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007feef835417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.
```

**Comment by mitzkia** [comment]
Unfortunately today I can not reproduce the issue.
I am trying to create a new, fix reproduction.

**Comment by mitzkia** [comment]
With the current syslog-ng and the given config I can not reproduce the issue.
