### ISSUE TITLE
sigsegv in qdisk_get_length

### ISSUE THREAD

**Issue by BruceHowells** [balabit/syslog-ng#1626]
# syslog-ng

## Version of syslog-ng

syslog-ng 3.10.1
Installer-Version: 3.10.1
Revision:
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: pseudofile,graphite,sdjournal,kvformat,date,cef,disk-buffer,add-contextual-data,tfgetent,map-value-pairs,stardate,snmptrapd-parser,syslogformat,afsocket,affile,afprog,afuser,afamqp,afmongodb,csvparser,confgen,system-source,linux-kmsg-format,basicfuncs,cryptofuncs,dbparser,json-plugin,afstomp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

## Platform

RHEL 7.3

# Issue

## Failure
```
[bhowells@lnx-syslog2p ~]$ sudo gdb /usr/local/sbin/syslog-ng core.21596
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/syslog-ng...done.
[New LWP 21596]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/sbin/syslog-ng -Fvd --enable-core '.
Program terminated with signal 11, Segmentation fault.
#0  qdisk_get_length (self=0x1002026f780) at modules/diskq/qdisk.c:926
926     }
Missing separate debuginfos, use: debuginfo-install glib2-2.46.2-4.el7.ppc64le glibc-2.17-157.el7_3.4.ppc64le json-c-0.11-4.el7_0.ppc64le keyutils-libs-1.5.8-3.el7.ppc64le krb5-libs-1.14.1-27.el7_3.ppc64le libcom_err-1.42.9-9.el7.ppc64le libselinux-2.5-6.el7.ppc64le openssl-libs-1.0.1e-60.el7_3.1.ppc64le pcre-8.32-15.el7_2.1.ppc64le zlib-1.2.7-17.el7.ppc64le
(gdb) bt full
#0  qdisk_get_length (self=0x1002026f780) at modules/diskq/qdisk.c:926
No locals.
#1  0x00003fff85d669b8 in _read_message (self=0x100202909a0, path_options=<optimized out>)
    at modules/diskq/logqueue-disk.c:264
        msg = 0x0
#2  0x00003fff85d67a04 in _pop_head (s=0x100202909a0, path_options=0x3fffeaaf2c10)
    at modules/diskq/logqueue-disk-non-reliable.c:258
        self = 0x100202909a0
        msg = <optimized out>
#3  0x00003fff85d66554 in _pop_head (s=0x100202909a0, path_options=0x3fffeaaf2c10)
    at modules/diskq/logqueue-disk.c:109
        self = 0x100202909a0
        msg = 0x0
#4  0x00003fff86b4e56c in log_queue_pop_head_ignore_throttle (path_options=0x3fffeaaf2c10,
    self=0x100202909a0) at lib/logqueue.h:128
No locals.
#5  log_writer_queue_pop_message (self=0x10020290420, force_flush=1, path_options=0x3fffeaaf2c10)
    at lib/logwriter.c:1169
No locals.
#6  log_writer_flush (self=0x10020290420, flush_mode=LW_FLUSH_FORCE) at lib/logwriter.c:1199
        path_options = {ack_needed = 1, flow_control_requested = 0, matched = 0x0}
        mark = -357618624
        write_error = 0
#7  0x00003fff86b4e7e8 in log_writer_deinit (s=0x10020290420) at lib/logwriter.c:1360
        self = 0x10020290420
#8  0x00003fff85dadb40 in log_pipe_deinit (s=0x10020290420) at ./lib/logpipe.h:285
        s = 0x10020290420
#9  affile_dw_deinit (s=0x100202ada40) at modules/affile/affile-dest.c:251
        self = 0x100202ada40
#10 0x00003fff85dad5f0 in log_pipe_deinit (s=0x100202ada40) at ./lib/logpipe.h:285
        s = 0x100202ada40
#11 affile_dd_reap_writer (dw=0x100202ada40, self=0x1002028a1b0) at modules/affile/affile-dest.c:431
        writer = <optimized out>
#12 affile_dw_reap (s=0x100202ada40) at modules/affile/affile-dest.c:142
        self = 0x100202ada40
#13 0x00003fff86b97bb8 in iv_run_timers (st=0x100202537a0) at iv_timer.c:149
        t = 0x100202adb10
#14 0x00003fff86b9a86c in iv_main () at iv_main_posix.c:107
        to = {tv_sec = 29, tv_nsec = 999982867}
#15 0x00003fff86b50154 in main_loop_run (self=0x3fff86bd6098 <main_loop>) at lib/mainloop.c:522
No locals.
#16 0x00000000100018d4 in main (argc=1, argv=0x3fffeaaf3368) at syslog-ng/main.c:301
        rc = 0
        ctx = <optimized out>
        error = 0x0
        main_loop = 0x3fff86bd6098 <main_loop>
        exit_before_main_loop_run = 0
```

## Steps to reproduce

1. start syslog-ng

2. generate log message

3. wait 1 minute

4. segfault.

## Configuration

```
@version: 3.10
@include "scl.conf"

options {
        create_dirs (yes);
        keep_hostname (yes);
};

source s_local {
        system();
        internal();
};

source s_network {
   network( max_connections(250) log_iw_size(25000) log_fetch_limit(100));
};

destination d_local {
        file("/data/messages/${HOST}/${YEAR}_${MONTH}_${DAY}.log"
        disk-buffer(
                mem-buf-size(1000)
                disk-buf-size(1048576)
                reliable(no)
                qout-size(64)
                )
        log_fifo_size(10000)
        );
};


log {
       source(s_network);
        destination(d_local);
};
```

## Input and output logs (if possible)

```
[2017-07-27T09:09:06.545594] Outgoing message; message='Jul 27 09:09:06 localhost \x1bquit\x0a'
[2017-07-27T09:09:19.459824] EOF occurred while reading; fd='12'
[2017-07-27T09:09:19.459864] Syslog connection closed; fd='12', client='AF_INET(127.0.0.1:56562)', local='AF_INET(0.0.0.0:514)'
[2017-07-27T09:09:19.459937] Closing log transport fd; fd='12'
[2017-07-27T09:10:35.551525] Destination timed out, reaping; template='/data/messages/${HOST}/${YEAR}_${MONTH}_${DAY}.log', filename='/data/messages/localhost/2017_07_27.log'
[2017-07-27T09:10:35.551630] Disk-buffer state saved; filename='/usr/local/var/syslog-ng-00011.qf', qout_length='0', qbacklog_length='0', qoverflow_length='0', qdisk_length='0'
$ 
```

**Comment by BruceHowells** [comment]
Answering from the other comment - yes, I'll be eventually using an NFS share.

**Comment by MrAnno** [comment]
Good news: this has been fixed in #1544. The upcoming release will contain the patch.

**Comment by BruceHowells** [comment]
Thank you!

**Comment by MrAnno** [comment]
Could you give it a try with [syslog-ng-3.11.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.11.1), please?

**Comment by BruceHowells** [comment]
I've got it burning in now, but the initial smoke test looks good.

Thank you!

**Comment by MrAnno** [comment]
You're welcome. Please don't forget to close this issue, if it has been resolved.

**Comment by BruceHowells** [comment]
Will reopen issue if weekend testing reveals issues.
