### ISSUE TITLE
Syslog-ng generating numerous dmesg messages (signal 6 core dumped)

### ISSUE THREAD

**Issue by Quux-NL** [balabit/syslog-ng#1712]
# syslog-ng

## Version of syslog-ng

```
output of syslog-ng --version
syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision: 
Compile-Date: Sep 18 2017 13:57:46
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: cef,tfgetent,dbparser,system-source,affile,afsocket,syslogformat,graphite,afprog,afuser,add-contextual-data,linux-kmsg-format,pseudofile,cryptofuncs,map-value-pairs,json-plugin,afamqp,stardate,disk-buffer,csvparser,snmptrapd-parser,confgen,date,kvformat,afstomp,basicfuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform

```
FreeBSD 10.3-RELEASE-p11
```

## Steps to reproduce

1. start syslog-ng

2. there is no step two

## Configuration

```
$ cat /path/to/syslog-ng.conf
@version:3.11
@include "scl.conf"

#
# This sample configuration file is essentially equilivent to the stock
# FreeBSD /etc/syslog.conf file.
#
# $FreeBSD: head/sysutils/syslog-ng/files/syslog-ng.conf.sample 340872 2014-01-24 00:14:07Z mat $
#

#
# options
#
options {
	keep_hostname(yes);
	chain_hostnames(off);
	create_dirs(yes);
#	flush_lines(0);
	threaded(yes);
	time_reap(30);
	mark_freq(10);
	dns_cache(2000);
	dns_cache_expire(87600);
	owner(root);            # owner of files
	group(wheel);           # group of files
	perm(0640);             # permissions for files
	dir_owner(root);
	dir_group(wheel);
	dir_perm(0750);
	log_fifo_size(4096);
#	stats_freq(3600);       # statistics frequency
};

#
# sources
#
source src {
	unix-dgram("/var/run/log");
	unix-dgram("/var/run/logpriv" perm(0600));
	internal();
	tcp(ip("46.XX.YY.ZZ") port(514));
	udp(ip("46.XX.YY.ZZ") port(514));
};

#
# destinations
#
destination messages { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/messages"); };
destination security { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/security"); };
destination authlog { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/auth.log"); };
destination maillog { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/maillog"); };
destination lpd-errs { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/lpd-errs"); };
destination xferlog { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/xferlog"); };
destination cron { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/cron"); };
destination debuglog { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/debug.log"); };
destination consolelog { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/console.log"); };
destination all { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/all.log"); };
destination newscrit { file("/var/log/news/$HOST/$YEAR.$MONTH.$DAY/news.crit"); };
destination newserr { file("/var/log/news/$HOST/$YEAR.$MONTH.$DAY/news.err"); };
destination newsnotice { file("/var/log/news/$HOST/$YEAR.$MONTH.$DAY/news.notice"); };
destination slip { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/slip.log"); };
destination ppp { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/ppp.log"); };
destination console { file("/var/log/$HOST/$YEAR.$MONTH.$DAY/console"); };
destination allusers { usertty("*"); };
#destination loghost { udp("loghost" port(514)); };

#
# log facility filters
#
filter f_auth { facility(auth); };
filter f_authpriv { facility(authpriv); };
filter f_not_authpriv { not facility(authpriv); };
#filter f_console { facility(console); };
filter f_cron { facility(cron); };
filter f_daemon { facility(daemon); };
filter f_ftp { facility(ftp); };
filter f_kern { facility(kern); };
filter f_lpr { facility(lpr); };
filter f_mail { facility(mail); };
filter f_news { facility(news); };
filter f_security { facility(security); };
filter f_user { facility(user); };
filter f_uucp { facility(uucp); };
filter f_local0 { facility(local0); };
filter f_local1 { facility(local1); };
filter f_local2 { facility(local2); };
filter f_local3 { facility(local3); };
filter f_local4 { facility(local4); };
filter f_local5 { facility(local5); };
filter f_local6 { facility(local6); };
filter f_local7 { facility(local7); };

#
# log level filters
#
filter f_emerg { level(emerg); };
filter f_alert { level(alert..emerg); };
filter f_crit { level(crit..emerg); };
filter f_err { level(err..emerg); };
filter f_warning { level(warning..emerg); };
filter f_notice { level(notice..emerg); };
filter f_info { level(info..emerg); };
filter f_debug { level(debug..emerg); };
filter f_is_debug { level(debug); };

#
# program filters
#
filter f_ppp { program("ppp"); };
filter f_slip { program("startslip"); };

#
# *.err;kern.warning;auth.notice;mail.crit		/dev/console
#
log { source(src); filter(f_err); destination(console); };
log { source(src); filter(f_kern); filter(f_warning); destination(console); };
log { source(src); filter(f_auth); filter(f_notice); destination(console); };
log { source(src); filter(f_mail); filter(f_crit); destination(console); };

#
# *.notice;authpriv.none;kern.debug;lpr.info;mail.crit;news.err	/var/log/messages
#
log { source(src); filter(f_notice); filter(f_not_authpriv); destination(messages); };
log { source(src); filter(f_kern); filter(f_debug); destination(messages); };
log { source(src); filter(f_lpr); filter(f_info); destination(messages); };
log { source(src); filter(f_mail); filter(f_crit); destination(messages); };
log { source(src); filter(f_news); filter(f_err); destination(messages); };

#
# security.*						/var/log/security
#
log { source(src); filter(f_security); destination(security); };

#
# auth.info;authpriv.info				/var/log/auth.log
log { source(src); filter(f_auth); filter(f_info); destination(authlog); };
log { source(src); filter(f_authpriv); filter(f_info); destination(authlog); };

#
# mail.info						/var/log/maillog
#
log { source(src); filter(f_mail); filter(f_info); destination(maillog); };

#
# lpr.info						/var/log/lpd-errs
#
log { source(src); filter(f_lpr); filter(f_info); destination(lpd-errs); };

#
# ftp.info						/var/log/xferlog
#
log { source(src); filter(f_ftp); filter(f_info); destination(xferlog); };

#
# cron.*						/var/log/cron
#
log { source(src); filter(f_cron); destination(cron); };

#
# *.=debug						/var/log/debug.log
#
log { source(src); filter(f_is_debug); destination(debuglog); };

#
# *.emerg						*
#
log { source(src); filter(f_emerg); destination(allusers); };

#
# uncomment this to log all writes to /dev/console to /var/log/console.log
# console.info						/var/log/console.log
#
#log { source(src); filter(f_console); filter(f_info); destination(consolelog); };

#
# uncomment this to enable logging of all log messages to /var/log/all.log
# touch /var/log/all.log and chmod it to mode 600 before it will work
# *.*							/var/log/all.log
#
#log { source(src); destination(all); };

#
# uncomment this to enable logging to a remote loghost named loghost
# *.*							@loghost
#
#log { source(src); destination(loghost); };

#
# uncomment these if you're running inn
# news.crit						/var/log/news/news.crit
# news.err						/var/log/news/news.err
# news.notice						/var/log/news/news.notice
#
#log { source(src); filter(f_news); filter(f_crit); destination(newscrit); };
#log { source(src); filter(f_news); filter(f_err); destination(newserr); };
#log { source(src); filter(f_news); filter(f_notice); destination(newsnotice); };

#
# !startslip
# *.*							/var/log/slip.log
#
log { source(src); filter(f_slip); destination(slip); };

#
# !ppp
# *.*							/var/log/ppp.log
#
log { source(src); filter(f_ppp); destination(ppp); };
```

## Input and output logs (if possible)

The dmesg-files are full with messages like this:

```
pid 87178 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87192 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87341 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87543 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87557 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87566 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87685 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87748 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87860 (syslog-ng), uid 0: exited on signal 6 (core dumped)
pid 87862 (syslog-ng), uid 0: exited on signal 6 (core dumped)
```

**Comment by Kokan** [comment]
@Quux-NL Could you please send possible the backtrack or the coredump ?
And the logs when you are executing the syslog-ng manually with `-Fdev`.

**Comment by Quux-NL** [comment]
Hi,

Trying to rebuild and install the port on FreeBSD results in the following error-code:

gmake[2]: Entering directory '/usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1'
/bin/sh /usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1/install-sh -d lib/rewrite/
./lib/merge-grammar.py lib/rewrite/rewrite-expr-grammar.ym > lib/rewrite/rewrite-expr-grammar.y
Traceback (most recent call last):
  File "./lib/merge-grammar.py", line 55, in <module>
    for line in fileinput.input():
  File "/usr/local/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/local/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
gmake[2]: *** [Makefile:17207: lib/rewrite/rewrite-expr-grammar.y] Error 1
gmake[2]: Leaving directory '/usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1'
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/sysutils/syslog-ng
*** Error code 1

Stop.
make: stopped in /usr/ports/sysutils/syslog-ng

**Comment by Quux-NL** [comment]
For your information I am running Python3.6

_=/usr/bin/env
SHELL=/usr/local/bin/ksh
...
PYTHONIOENCODING=utf8

[root @ colo]:/home/admin(594)# locale
LANG=
LC_CTYPE=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8

[root @ colo]:/home/admin(595)# portmaster -L
===>>> Root ports (No dependencies, not depended on)
===>>> beadm-1.2.7_2
===>>> dialog4ports-0.1.6
===>>> jailaudit-1.5.2
===>>> ksh93-20120801_2
===>>> lsof-4.90.p,8
===>>> pdksh-5.2.14p2_6
===>>> pkg-1.10.1
===>>> pkgconf-1.3.7,1
===>>> portmaster-3.17.10
===>>> smartmontools-6.5_2
===>>> ssmtp-2.64_2
===>>> 11 root ports

===>>> Trunk ports (No dependencies, are depended on)
===>>> autoconf-wrapper-20131203
===>>> automake-wrapper-20131203
===>>> ca_root_nss-3.32.1
===>>> dmidecode-3.1_1
===>>> e2fsprogs-libuuid-1.43.6
===>>> indexinfo-0.2.6
===>>> json-c-0.12.1
===>>> libbson-1.3.5
===>>> libevent-2.1.8
===>>> libiconv-1.14_11
===>>> libssh2-1.8.0,3
===>>> pcre-8.40_1
===>>> perl5-5.24.3
===>>> png-1.6.32
===>>> 14 trunk ports

===>>> Branch ports (Have dependencies, are depended on)
===>>> autoconf-2.69_1
===>>> curl-7.55.1
===>>> gettext-runtime-0.19.8.1_1
===>>> glib-2.50.2_6,1
===>>> libffi-3.2.1_1
===>>> libgit2-0.25.1_1
===>>> libslang2-2.3.1_1
===>>> m4-1.4.18,1
===>>> p5-Locale-gettext-1.07
===>>> py36-Babel-2.3.4
===>>> py36-Jinja2-2.9.5
===>>> py36-MarkupSafe-1.0
===>>> py36-alabaster-0.7.6
===>>> py36-certifi-2017.7.27.1
===>>> py36-cffi-1.7.0
===>>> py36-chardet-3.0.4
===>>> py36-click-6.7
===>>> py36-coloredlogs-7.3
===>>> py36-cryptography-2.0.3
===>>> py36-docutils-0.14
===>>> py36-humanfriendly-4.4.1
===>>> py36-idna-2.5
===>>> py36-imagesize-0.7.1
===>>> py36-libzfs-1.0.20170814
===>>> py36-openssl-17.3.0
===>>> py36-pyasn1-0.2.2
===>>> py36-pycparser-2.10
===>>> py36-pygit2-0.25.1
===>>> py36-pygments-2.2.0
===>>> py36-pysocks-1.6.7
===>>> py36-pystemmer-1.3.0_1
===>>> py36-pytest-runner-2.11.1
===>>> py36-pytz-2017.2,1
===>>> py36-requests-2.18.1_1
===>>> py36-setuptools-36.2.2
===>>> py36-six-1.11.0
===>>> py36-snowballstemmer-1.2.0_1
===>>> py36-sphinx_rtd_theme-0.2.4
===>>> py36-texttable-0.9.1
===>>> py36-tqdm-4.18.0
===>>> py36-urllib3-1.22
===>>> py36-verboselogs-1.6
===>>> python3-3_3
===>>> python36-3.6.2_1
===>>> readline-7.0.3
===>>> 45 branch ports

===>>> Leaf ports (Have dependencies, not depended on)
===>>> automake-1.15.1
===>>> bash-4.4.12_2
===>>> gettext-tools-0.19.8.1
===>>> gmake-4.2.1_1
===>>> help2man-1.47.5
===>>> libtool-2.4.6
===>>> most-5.0.0_2
===>>> py36-iocage-0.9.9.1_1
===>>> py36-setuptools_scm-1.15.5
===>>> py36-sphinx-1.4.8_2,1
===>>> rsync-3.1.2_7
===>>> sudo-1.8.21p2
===>>> sysinfo-1.0.1_2
===>>> syslog-ng-3.11.1_1
===>>> tmux-2.5_1
===>>> 15 leaf ports

===>>> 85 total installed ports

**Comment by Kokan** [comment]
The current build system requires you to have python2.

**Comment by furiel** [comment]
Without further information (core dump backtrace and error logs), I'm afraid this cannot be investigated further.

Slightly related: 
Since https://github.com/balabit/syslog-ng/pull/1868 the grammar generation works with both python2 and python3.
Since https://github.com/balabit/syslog-ng/pull/2472 python is not required if syslog-ng is built from tarball (not git source).

Closing this due to inactivity.
