### ISSUE TITLE
Segfault on Debian Stretch

### ISSUE THREAD

**Issue by bobrik** [balabit/syslog-ng#1768]
# syslog-ng

## Version of syslog-ng

```
$ sudo syslog-ng --version
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 3.8.1-10
Module-Directory: /usr/lib/syslog-ng/3.8
Module-Path: /usr/lib/syslog-ng/3.8
Available-Modules: system-source,syslogformat,pseudofile,linux-kmsg-format,kvformat,disk-buffer,dbparser,date,csvparser,cryptofuncs,confgen,cef,basicfuncs,afuser,afsocket,afprog,affile,sdjournal
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

## Platform

Debian Stretch

# Issue

## Failure

```
Core was generated by `/usr/sbin/syslog-ng -F --fd-limit 100000 --worker-threads 4'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f3a6215f700 (LWP 4933))]
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007f3a85e77aa4 in log_msg_refcache_stop () at ../../lib/logmsg/logmsg.c:1644
        ack_type_cumulated = AT_PROCESSED
        current_cached_acks = <optimized out>
        current_cached_abort = 0
        current_cached_suspend = 0
        __func__ = "log_msg_refcache_stop"
#2  0x00007f3a85e4b40c in log_writer_write_message (self=self@entry=0x556c0f9eca50, msg=0x556c0fa2d7c0, path_options=path_options@entry=0x7f3a6215c970, write_error=write_error@entry=0x7f3a6215c96c)
    at ../../lib/logwriter.c:1147
        consumed = 1
#3  0x00007f3a85e4b655 in log_writer_flush (self=0x556c0f9eca50, flush_mode=LW_FLUSH_NORMAL) at ../../lib/logwriter.c:1205
        path_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
        write_error = 0
#4  0x00007f3a85e4b76a in log_writer_work_perform (s=0x556c0f9eca50) at ../../lib/logwriter.c:185
        self = 0x556c0f9eca50
#5  0x00007f3a85e4d34d in _work (self=<optimized out>) at ../../lib/mainloop-io-worker.c:52
No locals.
#6  0x00007f3a84847da7 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
No symbol table info available.
#7  0x00007f3a84847073 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
No symbol table info available.
#8  0x00007f3a84849a6c in iv_main () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
No symbol table info available.
#9  0x00007f3a84847bf4 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
No symbol table info available.
#10 0x00007f3a8484a6c8 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
No symbol table info available.
#11 0x00007f3a8462d494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#12 0x00007f3a8436faff in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
```

## Steps to reproduce

1. Start syslog-ng
2. Wait for some time
3. ???
4. Observe segfault

**Comment by Kokan** [comment]
Hello,

@bobrik could you please share your configuration ?

**Comment by furiel** [comment]
I am closing this due to inactivity. If the problem still persists, please try to reproduce with a more recent version. A lot of things have changed since 3.8.1. Also, please share a minimal configuration, and any other thing that can help us reproduce and locate the problem.
