### ISSUE TITLE
SigSegv on Artful while using tls keys

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#1882]
With the following mutual authenticated TLS setup syslog-ng can crash on Ubuntu Artful. This issue can not reproduced in Ubuntu Xenial
Client config:
 * source: file
 * destination: network with proper tls keys

Server config:
 * source: network with proper tls keys
 * destination: file

Reproduction:
1, start both syslog-ng (client, server)
2, start reloading client side (with sleep 1 delay)
3, start sending log on client side

bt:
```
Core was generated by `sbin/syslog-ng -Fedv -f /home/micek/ssl_test/syslog_ng_ssl_client.conf -c clien'.
--
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f98e9cc862d in tls_context_get_verify_mode (self=0x20) at ../lib/tlscontext.c:787
---Type <return> to continue, or q <return> to quit---
787	  return self->verify_mode;
[Current thread is 1 (Thread 0x7f98e5766700 (LWP 28057))]
(gdb) bt full
#0  0x00007f98e9cc862d in tls_context_get_verify_mode (self=0x20) at ../lib/tlscontext.c:787
No locals.
#1  0x00007f98e67c20ed in afinet_dd_verify_callback (ok=1, ctx=0x7f98e5763490, user_data=0x55c1b0840130) at ../modules/afsocket/afinet-dest.c:105
self = 0x55c1b0840130
transport_mapper_inet = 0x55c1b08400a0
current_cert = 0x7f98d8002a40
cert = 0x7f98d8002a40
#2  0x00007f98e9cc7307 in tls_session_verify_callback (ok=1, ctx=0x7f98e5763490) at ../lib/tlscontext.c:246
ssl = 0x55c1b08060c0
self = 0x55c1b082d9f0
#3  0x00007f98e7ceea7b in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
No symbol table info available.
#4  0x00007f98e7cf083c in X509_verify_cert () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
No symbol table info available.
#5  0x00007f98e801c782 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#6  0x00007f98e7ff7aae in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#7  0x00007f98e7ffc802 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#8  0x00007f98e800637d in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#9  0x00007f98e8006832 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#10 0x00007f98e9cc9af7 in log_transport_tls_write_method (s=0x55c1b08207d0, buf=0x55c1b0801230, buflen=90)
at ../lib/transport/transport-tls.c:111
self = 0x55c1b08207d0
ssl_error = 32664
rc = -445224512
#11 0x00007f98e9ce06e6 in log_transport_write (self=0x55c1b08207d0, buf=0x55c1b0801230, count=90) at ../lib/transport/logtransport.h:45
No locals.
#12 0x00007f98e9ce07ec in log_proto_text_client_flush (s=0x55c1b0826000) at ../lib/logproto/logproto-text-client.c:54
len = 90
self = 0x55c1b0826000
rc = 32664
#13 0x00007f98e9ce09ef in log_proto_text_client_post (s=0x55c1b0826000,
msg=0x7f98e00040f0 "<13>Feb  6 11:15:00 tristram sad askjd alskjd laksjd lsakjdsalk jdalks jdlsakj dlsakj - 2\n", msg_len=90,
consumed=0x7f98e5763890) at ../lib/logproto/logproto-text-client.c:126
---Type <return> to continue, or q <return> to quit---
self = 0x55c1b0826000
rc = 32664
#14 0x00007f98e9cb4e08 in log_proto_client_post (s=0x55c1b0826000,
msg=0x7f98e00040f0 "<13>Feb  6 11:15:00 tristram sad askjd alskjd laksjd lsakjdsalk jdalks jdlsakj dlsakj - 2\n", msg_len=90,
consumed=0x7f98e5763890) at ../lib/logproto/logproto-client.h:118
No locals.
#15 0x00007f98e9cb7142 in log_writer_write_message (self=0x55c1b080e0d0, msg=0x7f98e0005120, path_options=0x7f98e57638d0,
write_error=0x7f98e57638c0) at ../lib/logwriter.c:1108
status = (unknown: 32664)
consumed = 0
#16 0x00007f98e9cb73ca in log_writer_flush (self=0x55c1b080e0d0, flush_mode=LW_FLUSH_NORMAL) at ../lib/logwriter.c:1205
path_options = {ack_needed = 0, flow_control_requested = 0, matched = 0x0}
msg = 0x7f98e0005120
mark = 0
write_error = 0
#17 0x00007f98e9cb50c3 in log_writer_work_perform (s=0x55c1b080e0d0) at ../lib/logwriter.c:184
self = 0x55c1b080e0d0
__func__ = "log_writer_work_perform"
#18 0x00007f98e9cba3cb in _work (self=0x55c1b080e2e8) at ../lib/mainloop-io-worker.c:53
No locals.
#19 0x00007f98e9d0b819 in iv_work_thread_got_event (_thr=0x55c1b080d250) at ../../../../lib/ivykis/src/iv_work.c:106
work = 0x55c1b080e308
thr = 0x55c1b080d250
pool = 0x55c1b08022d0
last_seq = 58
#20 0x00007f98e9d09ff1 in __iv_event_run_pending_events (_st=0x7f98d8000b10) at ../../../../lib/ivykis/src/iv_event.c:56
ie = 0x55c1b080d270
empty_now = 1
st = 0x7f98d8000b10
events = {next = 0x7f98e57639d0, prev = 0x7f98e57639d0}
#21 0x00007f98e9d0a71a in iv_run_tasks (st=0x7f98d8000b10) at ../../../../lib/ivykis/src/iv_task.c:48
t = 0x7f98d8000b20
tasks = {next = 0x7f98e5763a30, prev = 0x7f98e5763a30}
epoch = 1
#22 0x00007f98e9d0e08b in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:99
_abs = {tv_sec = 140294661487264, tv_nsec = 4294967296}
abs = 0x7f98e5763aa0
st = 0x7f98d8000b10
---Type <return> to continue, or q <return> to quit---
run_timers = 1
#23 0x00007f98e9d0bac5 in iv_work_thread (_thr=0x55c1b080d250) at ../../../../lib/ivykis/src/iv_work.c:185
thr = 0x55c1b080d250
pool = 0x55c1b08022d0
#24 0x00007f98e9d0f364 in iv_thread_handler (_thr=0x55c1b0822ab0) at ../../../../lib/ivykis/src/iv_thread_posix.c:112
thr = 0x55c1b0822ab0
#25 0x00007f98e973f7fc in start_thread (arg=0x7f98e5766700) at pthread_create.c:465
pd = 0x7f98e5766700
now = <optimized out>
unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140294661498624, -799557890377886106, 140733373844958, 140733373844959, 140294661498624,
140294661499328, 853059093366724198, 853067857392195174}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
prev = 0x0, cleanup = 0x0, canceltype = 0}}}
not_first_call = <optimized out>
pagesize_m1 = <optimized out>
sp = <optimized out>
freesize = <optimized out>
__PRETTY_FUNCTION__ = "start_thread"
#26 0x00007f98e946cb5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by mitzkia** [comment]
Ok, verified. With the current syslog-ng v3.19 I can not reproduce this issue.
Tested version: abd8814122525caf4d08dcf755e30aed475915df
