### ISSUE TITLE
SIGSEGV when trying to revert to old config

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#203]
1. Start syslog-ng with the following valid config:

>     @version:5.0
>     source si_local {
>      tcp(
>      ip("127.0.0.1")
>      port(10514)
>      );
>     };
>     destination di_program {
>      program("read");
>     };
>     log {
>      source(si_local);
>      destination(di_program);
>      destination(d_sql);
>     };
>     destination d_sql {
>      sql(
>      type("mysql")
>      columns("insert_time int", "rule_id varchar(40)",
>              "__row_id serial", "polipolore varchar(1024)")
>      values("${R_UNIXTIME}", "${.classifier.rule_id}", default, "asdf")
>      indexes("insert_time", "rule_id", )
>      );
>     };

2. Replace the config with the following invalid config:

>     @version:5.0
>     source si_local {
>      tcp(
>      ip("127.0.0.1")
>      port(10514)
>      );
>     };
>     destination di_program {
>      program("read");
>     };
>     log {
>      source(si_local);
>      destination(di_program);
>      destination(d_sql);
>     };
>     destination d_sql {
>      sql(
>      type("mysql")
>      columns("insert_time int", "rule_id varchar(40)",
>              "__row_id serial", "poli-polore varchar(1024)")
>      values("${R_UNIXTIME}", "${.classifier.rule_id}", default, "asdf")
>      indexes("insert_time", "rule_id", )
>      );
>     };

3. send infinite reload to syslog-ng: `while true ; do kill -1 [syslog-ng pid] ; done`

backtrace:

```
Core was generated by `./syslog-ng -Fedv'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7d80bcb0a6 in plugin_find (cfg=0x0, plugin_type=18, plugin_name=0x7f7d7f026636 "text") at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/plugin.c:145
145	  p = plugin_find_in_list(cfg, cfg->plugins, plugin_type, plugin_name);
(gdb) bt full
#0  0x00007f7d80bcb0a6 in plugin_find (cfg=0x0, plugin_type=18, plugin_name=0x7f7d7f026636 "text") at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/plugin.c:145
        p = 0x7fff4a9e7b70
        candidate = 0x7f7d7f020bca <transport_mapper_inet_apply_transport_method+66>
#1  0x00007f7d80be5193 in log_proto_server_get_factory (cfg=0x0, name=0x7f7d7f026636 "text") at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/logproto/logproto-server.c:204
        plugin = 0x8ae270
#2  0x00007f7d7f01ca68 in afsocket_sd_setup_transport (self=0x8ae2f0) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsocket/afsocket-source.c:460
        cfg = 0x0
#3  0x00007f7d7f01d085 in afsocket_sd_init_method (s=0x8ae2f0) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsocket/afsocket-source.c:632
        self = 0x8ae2f0
#4  0x00007f7d7f01f1ba in afinet_sd_init (s=0x8ae2f0) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsocket/afinet-source.c:105
        self = 0x8ae2f0
#5  0x00007f7d80bac13b in log_pipe_init (s=0x8ae2f0) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/logpipe.h:264
No locals.
#6  0x00007f7d80bae1b8 in cfg_tree_start (self=0x7df588) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/cfg-tree.c:1077
        pipe = 0x8ae2f0
        i = 0
#7  0x00007f7d80ba762e in cfg_init (cfg=0x7df400) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/cfg.c:229
        regerr = 18
#8  0x00007f7d80bc3785 in main_loop_reload_config_apply () at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/mainloop.c:215
        __PRETTY_FUNCTION__ = "main_loop_reload_config_apply"
#9  0x00007f7d80bc4d76 in main_loop_worker_job_complete () at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/mainloop-worker.c:237
No locals.
#10 0x00007f7d80bc44c1 in main_loop_call_handler (user_data=0x0) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/mainloop-call.c:113
        site = 0x7f7d810315d8
        result = 0xffffffffffffffff
#11 0x00007f7d7f648bdf in __iv_event_run_pending_events (_tinfo=0x7d2630) at iv_event.c:58
        ie = 0x7f7d80e36be0 <main_task_posted>
        tinfo = 0x7d2630
        events = {next = 0x7fff4a9e7e50, prev = 0x7fff4a9e7e50}
#12 0x00007f7d7f64a213 in iv_event_raw_got_event (_this=0x7d2638) at iv_event_raw_posix.c:89
        this = 0x7d2638
        buf = "\001", '\000' <repeats 15 times>, "\377\000\377\377\377\377\377\377\377\000\000\000\000\000\000\000", '%' <repeats 16 times>, "@!#?\000%d:%d\000line", '\000' <repeats 17 times>, "\377\000\377\377\377\377\377\377\377", '\000' <repeats 39 times>, "\377\377\377\377\377\377\377\377\000\000\377\377\377\377", '\000' <repeats 67 times>...
        ret = <optimized out>
#13 0x00007f7d7f64a890 in iv_fd_poll_and_run (st=st@entry=0x7d25c0, to=to@entry=0x7fff4a9e8300) at iv_fd.c:163
        fd = 0x7d2648
        active = {next = 0x7fff4a9e82d0, prev = 0x7fff4a9e82d0}
---Type <return> to continue, or q <return> to quit---
#14 0x00007f7d7f64b854 in iv_main () at iv_main_posix.c:117
        to = {tv_sec = 583, tv_nsec = 777369606}
#15 0x00007f7d80bc3d80 in main_loop_run () at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/mainloop.c:491
No locals.
#16 0x0000000000401a5b in main (argc=1, argv=0x7fff4a9e8458) at /home/micek/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/syslog-ng/main.c:270
        rc = 0
        ctx = 0x7d1cf0
        error = 0x0
```

```
version:
syslog-ng 3.6.0alpha1
Installer-Version: 3.6.0alpha1
Revision: syslog-ng-ose-3.6/syslog-ng--mainline--3.6--master#74ff463acae0a09fe5a7b964d988c97391e0cc27
Compile-Date: Aug 14 2014 16:39:01
Available-Modules: syslogformat,afsocket-tls,basicfuncs,tfgeoip,afsocket,cryptofuncs,afsocket-notls,afsql,confgen,json-plugin,pseudofile,system-source,affile,redis,afuser,afsmtp,csvparser,dbparser,afstomp,linux-kmsg-format,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

**Comment by u2yg** [comment]
Works for me.
