### ISSUE TITLE
Patterndb file not accepted - no verbose error msg

### ISSUE THREAD

**Issue by T4iga** [balabit/syslog-ng#2180]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.16.1)
Config version: 3.16
Installer-Version: 3.16.1
Revision: 
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Available-Modules: add-contextual-data,affile,afmongodb,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml,mod-java
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform
OpenSuse 42.3

## Debug bundle

```
I created a bundle but i am not sure how to post it here since it contains so many files and is 1.5M in size.
```

# Issue
PatternDB crashes without error.
Fixed all errors it threw. Now i only get 
log4j:ERROR Could not read configuration file [null].
and a stack trace

Message logging to local file destinations works fine. 
## Failure

```
# syslog-ng
log4j:ERROR Could not read configuration file [null].
java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
	at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.<clinit>(ESHttpClient.java:67)
	at org.syslog_ng.elasticsearch_v2.client.ESClientFactory.getESClient(ESClientFactory.java:43)
	at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.init(ElasticSearchDestination.java:57)
	at org.syslog_ng.LogPipe.initProxy(LogPipe.java:64)
log4j:ERROR Ignoring configuration file [null].
[main] INFO io.searchbox.client.AbstractJestClient - Setting server pool to a list of 1 servers: [http://127.0.0.1:9200]
[main] INFO io.searchbox.client.JestClientFactory - Using multi thread/connection supporting pooling connection manager
[main] INFO io.searchbox.client.JestClientFactory - Using default GSON instance
[main] INFO io.searchbox.client.JestClientFactory - Node Discovery disabled...
[main] INFO io.searchbox.client.JestClientFactory - Idle connection reaping disabled...
```
## Configuration
# cat /path/to/syslog-ng.conf
```
############### Globale Optionen ###############
@version:3.16.1
@module mod-java               # Elasticsearch .jar-libraries are located in /opt/syslog-ng/lib/syslog-ng/java-modules/
@include "scl.conf"

options {
	chain_hostnames(off);	# Standard
	flush_lines(0); 	# Standard
	perm(0640); 		# Standard
	stats_freq(3600); 	# Standard
	threaded(yes);		# Standard 
	create-dirs(yes);       # erlaubt Syslog-NG, falls noetig, neue Verzeichnisse anzulegen
	dir-owner(root);        # die neuen Verzeichnisse gehoeren root
	dir-perm(0640);         # entspricht -rw-r-----, Besitzer: Lesen, Schreiben; Gruppe: Lesen; Alle: Nichts
	file-template(t_myLoggingFormat); # legt Standart-Template fuer file Destinations fest
#	threaded(yes);		# Example config Elasticsearch2
#	use-uniqid(yes);	# Example config Elasticsearch2
};

############### Sources - Quellen ###############
# Fuer interne Nachrichten
source s_myInternalSource {
        system();       # von Betriebssystem und aehnlichem
        internal();     # Syslog-interne Nachrichten
};

# Fuer Netzwerk-Nachrichten
source s_myNetworkSource {
        ### UDP beide Ports, RFC3164 und RFC5424 ####
	syslog(
        	ip(0.0.0.0)	 # 
        	port(601)	 # Standardport für legacy RFC 3164 UDP syslog 
        	transport("udp") #
        );

	syslog(
		ip(0.0.0.0)	 #
		port(514)	 # Non-Standardport
		transport("udp") #
	);

	syslog(
                ip(0.0.0.0)	 # Bedeutet NICHT, das von allen angenommen wird, siehe filter
                port(601)	 # Standardport für RFC 5424 TCP Syslog ist 601
                transport("tcp") # TCP, damit Nachrichten garantiert am Ziel ankommen
        );
	syslog(
		ip(0.0.0.0)	 #
		port(514)	 # Non-Standard Port
		transport("tcp") #
	);
};

############### Templates - Vorlagen ###############
# Aufbau des Nachrichteninhalts fuer Dateiziele
template t_myLoggingFormat {
	template("$(padding ${FULLHOST} 15 ' ')|${ISODATE}|PRI:$(padding ${PRI} 3 ' ')|${MSGHDR} ${MSG}\n");
};

# Legacy-Nachrichten werden anders geparst
# Mit Standardtempalte wir die Originalnachricht vollständig in MSG eingefügt

# Fuer Nachrichtenpfad
# Dateiname ist Tag(Nummer innerhalb des Monats)-Kuerzel(Mon, Tue, Wen, Thu, Fri, Sat, Sun)
# zum Beispiel "127.0.0.1/2018/Jan/17-Sat"
template t_destination {
	template("${FULLHOST}/${YEAR}/${YEAR}-${MONTH_ABBREV}-${DAY}.log");
};
        
############### Filter ###############
# Ein Filter je Quelle
# Filter kann man so machen: 
# filter <filter-id>
# {"<macro-or-template>" operator "<value-or-macro-or-template>"};
# oder mit Functions
filter f_noDebug { 
        level(emerg..info);		# Schließt Debug-Nachrichten aus 
};

filter f_networkfilter { 		
};

filter f_checkpoints {
};


############### Rewrite Rules ######################
rewrite r_checkpoint_remove_irrelevant {
	subst(
		'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} - ',
		'',
		type("pcre"),
		value("MESSAGE") flags("utf8" "store-matches")
	);

};

############### Parser #############################
parser p_pattern_db {
	db-parser(
		file("/opt/syslog-ng/etc/patterndb.xml-checkpoint")
	);
};

############### Ziele - Destinations ###############
# Ein Ziel fuer jede IP-Adresse, Jahr, Monat, Tag, etc
destination d_myDestination {
	file("/var/log/syslog-ng/$FULLHOST/$YEAR/$YEAR-$MONTH-$DAY.log"
		create_dirs(yes)
	);
};

destination d_testination {
	file("/var/log/syslog-ng/test/$FULLHOST/$YEAR/$YEAR-$MONTH-$DAY.log"
		create_dirs(yes)
	); 
};

destination d_elasticsearch {
	elasticsearch2(
		cluster("syslog-ng")
		cluster-url("http://127.0.0.1:9200")
		client-mode("http")
#		https-auth-type(basic)
#		http-auth-type-basic-password()
#		http-auth-type-basic-username()
		index("syslog-ng")
		type("test")
#	default template($(format-json --scope rfc5424 --exclude DATE --key ISODATE @timestamp=${ISODATE}))
#		template("$(format-json --scope rfc5424 --scope nv-pairs --exclude DATE --key ISODATE)")
	)
};
############### Log-Pfade ###############
# 
log {
	source(s_myNetworkSource);		# Fuer TCP und UDP Nachrichten von allen Clients
	source(s_myInternalSource);		# interne Nachrichten
	filter(f_networkfilter);		
	filter(f_noDebug);        		# alle außer debug
        destination(d_myDestination);		# universal Ziel; siehe Template
};
#
log {   ###### Checkpoints #######
        source(s_myNetworkSource);
        filter(f_checkpoints);          # Nur Checkpoint-Non-Standard
        filter(f_noDebug);
	rewrite(r_checkpoint_remove_irrelevant);
        destination(d_myDestination);
};
#
log {   ###### Elasticsearch ######
        source(s_myNetworkSource);
        source(s_myInternalSource);
        parser(p_pattern_db);
        destination(d_elasticsearch);
        flags(flow-control);
};

#
#log {	# for testing purposes
#	source(s_myNetworkSource);
#	source { syslog( ip( 0.0.0.0) transport("udp") flags(syslog-protocol); };	
#	destination(d_testination);
#};

############################## ENDE ##############################
```
# cat /path/to/patterndb.xml 
```
<?xml version='1.0' encoding='UTF-8'?>
<patterndb version='3' pub_date='2018-07-10'>
  <ruleset name='juniper'>
    <description>
      This ruleset covers the Messages sent by PulseSecure.
    </description>
    <url>https://kb.pulsesecure.net/articles/Pulse_Secure_Article/KB40143</url>
    <pattern>PulseSecure</pattern>
    <rules>

      <rule provider="Niklas Deffner" id="1" class="Firewall">
        <patterns>
          <pattern>psa@NUMBER:fw.id@ - [@IPv4:client.ip@] @ESTRING:client.hostname:()@@QSTRING:exchange.name:[:]@ - WebRequest ok : Host: @ESTRING:exchange.hostname:,@ Request: /Microsoft-Server-ActiveSync?User=@ESTRING:client.hostname:&amp;@DeviceId=@ESTRING:client.id:&amp;@DeviceType=@ESTRING:client.type:&amp;@Cmd=@STRING@@ANYSTRING@</pattern>
        </patterns> 
        <examples>
        </examples>
        <values>
        </values>
        <tags>
          <tag>WebRequest ok</tag>
        </tags>
      </rule>

      <rule provider="Niklas Deffner" id="2" class="Firewall">
        <patterns>
          <pattern>psa@NUMBER:fw.id@ - [@IPv4:client.ip@] @ESTRING:client.hostname:()@@QSTRING:exchange.name:[:]@ - WebRequest completed, POST to https://@ESTRING:exchange.hostname::@443//Microsoft-Server-ActiveSync?User=@ESTRING:client.hostname.url:&amp;@DeviceId=@ESTRING:client.id:&amp;@DeviceType=@ESTRING:client.type:&amp;@Cmd=@STRING:client.command@ from @IPv4:exchange.ip@ result=@NUMBER:result@ sent=@NUMBER:sent@ received=@NUMBER:received@ in @NUMBER:time@ seconds@ANYSTRING@</pattern>
        </patterns>
        <examples>
        </examples>
        <values>
        </values>
        <tags>
          <tag>WebRequest completed</tag>
        </tags>
      </rule>

      <rule provider="Niklas Deffner" id="3" class="Firewall">
        <patterns>
          <pattern>psa@NUMBER:fw.id@ - [@IPv4:client.ip@] @ESTRING:client.name:()@@QSTRING:exchange.name:[:]@ - WebRequest ok : Host: @ESTRING:exchange.hostname:,@ Request: /Microsoft-Server-ActiveSync?Cmd=@ESTRING:client.command:&amp;@User=@ESTRING:client.hostname.url:&amp;@DeviceId=@ESTRING:client.id:&amp;@DeviceType=@STRING:client.type@@ANYSTRING@</pattern>
        </patterns>
        <examples>
        </examples>
        <values>
        </values>
        <tags>
          <tag>WebRequest ok</tag>
          <tag> </tag>
        </tags>
      </rule>

      <rule provider="Niklas Deffner" id="4" class="Firewall">
        <patterns>
          <pattern>psa@NUMBER:fw.id@ - [@IPv4:client.ip@] @ESTRING:client.name:()@@QSTRING:exchange.name:[:]@ - WebRequest completed, POST to https://@ESTRING:exchange.hostname::@443//Microsoft-Server-ActiveSync?Cmd=@ESTRING:client.command:&amp;@User=@ESTRING:client.hostname.url:&amp;@DeviceId=@ESTRING:client.id:&amp;@DeviceType=@STRING:client.type@ from @IPv4:exchange.ip@ result=@NUMBER:result@ received=@NUMBER:received@ sent=@NUMBER:sent@ in @STRING:time@ @ANYSTRING@</pattern>
        </patterns>
        <examples>
        </examples>
        <values>
        </values>
        <tags>
          <tag>WebRequest completed</tag>
          <tag> </tag>
        </tags>
      </rule>
    </rules>
  </ruleset>
</patterndb>
```

**Comment by MrAnno** [comment]
Hi @T4iga,

It looks like your PatternDB configuration is syntactically correct, syslog-ng accepts it.
You mentioned a PatternDB crash. Did you mean the `java.lang.NullPointerException` with the stacktrace?

The stacktrace and the log4j errors are coming from our Java language binding, which has nothing to do with PatternDB.
This is from the `elasticsearch2` destination you've configured above.

I'll have a deeper look on this NullPointerException and we'll propose a fix, but this error is not fatal, your configuration should just work fine (even the PatternDB parser and the elasticsearch2 destination).

**Comment by MrAnno** [comment]
You're welcome.
