### ISSUE TITLE
log4j:ERROR Could not read configuration file [null].

### ISSUE THREAD

**Issue by JawadKM** [balabit/syslog-ng#2292]
Hi,
I am using syslog-ng to push logs to Elasticsearch, after configuring syslog-ng I am receiving the following Error.

log4j:ERROR Could not read configuration file [null].
java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
        at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.<clinit>(ESHttpClient.java:67)
        at org.syslog_ng.elasticsearch_v2.client.ESClientFactory.getESClient(ESClientFactory.java:43)
        at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.init(ElasticSearchDestination.java:57)
        at org.syslog_ng.LogPipe.initProxy(LogPipe.java:64)
log4j:ERROR Ignoring configuration file [null].
[main] INFO io.searchbox.client.AbstractJestClient - Setting server pool to a list of 1 servers: [http://localhost:9200]
[main] INFO io.searchbox.client.JestClientFactory - Using multi thread/connection supporting pooling connection manager
[main] INFO io.searchbox.client.JestClientFactory - Using default GSON instance
[main] INFO io.searchbox.client.JestClientFactory - Node Discovery disabled...
[main] INFO io.searchbox.client.JestClientFactory - Idle connection reaping disabled...

**Version of my syslog-ng**

syslog-ng 3 (3.14.1)
Config version: 3.14
Installer-Version: 3.14.1
Revision:
Compile-Date: Feb 28 2018 07:34:20
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: add-contextual-data,afamqp,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml,mod-java
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

**Syslog-ng Config for Elasticsearch**

destination d_elastic {
elasticsearch2 (
cluster("syslog-ng")
client-mode("http")
index("syslog-ng")
type("test")
template("$(format-json --scope rfc5424 --scope nv-pairs --exclude DATE --key ISODATE)")
)
};

log {
source(s_network);
destination(d_elastic);
flags(flow-control);
};

**My main Syslog-ng Conf file**

@version:3.14
@include "scl.conf"

# syslog-ng configuration file.
#
# This should behave pretty much like the original syslog on RedHat. But
# it could be configured a lot smarter.
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#
# Note: it also sources additional configuration files (*.conf)
#       located in /etc/syslog-ng/conf.d/

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

source s_sys {
    system();
    internal();
    # udp(ip(0.0.0.0) port(514));
};

#Following config pushes application logs comming in from network to ELK

source s_network {
        syslog(transport(tcp) port(514));
};

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/messages"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" flush_lines(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_kern { file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

filter f_kernel     { facility(kern); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };

#log { source(s_sys); filter(f_kernel); destination(d_cons); };
log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };

# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"

# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

your help in this regard will be highly appriciated.

**Comment by gaborznagy** [comment]
Hi @JawadKM,

Sorry if I don't understand it entirely, your issue is about the java exception regarding log4j?

You can configure log4j usage via `jvm_options` in the configuration's global options section:
```
options {
  jvm_options("-Dlog4j.configuration=file:/some/javalib/config/log4j.properties -Dlog4j.debug=true");
};
```

**Comment by JawadKM** [comment]
Hi, sorry for the lame question, but I cant find the path for log4j.properties
can you pleas guide me where I can find it.

**Comment by faxm0dem** [comment]
I think there is none in the distribution. hence the error message ;-)
In other words, you need to create one from scratch.
Admittedly, syslog-ng ought to ship one.

**Comment by JawadKM** [comment]
Hi again,
Problem is I have the same configuration in my lab and its working. 
Where as in Dev Syslog-ng is working in background but I just cant start it/ restart after the config change and it keeps on giving the same error

**Comment by JawadKM** [comment]
Hi,
Elasticsearch contains a log4j2.properties file under their directory. but if we try to point syslog-ng to use that file (as you suggested), it says (No such file or directory) even if the file is there. We have even tried to set the permission to 777 and still not found.

```
# /usr/sbin/syslog-ng -F $SYSLOGNG_OPTS -p /var/run/syslogd.pid
log4j: Using URL [file:/etc/elasticsearch/log4j2.properties] for automatic log4j configuration.
log4j: Reading configuration from URL file:/etc/elasticsearch/log4j2.properties
log4j: Could not find root logger information. Is this OK?
log4j: Finished configuring.
log4j:ERROR Could not read configuration file [file:/etc/elasticsearch/log4j2.properties].
java.io.FileNotFoundException: file:/etc/elasticsearch/log4j2.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
        at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.<clinit>(ESHttpClient.java:67)
        at org.syslog_ng.elasticsearch_v2.client.ESClientFactory.getESClient(ESClientFactory.java:43)
        at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.init(ElasticSearchDestination.java:57)
        at org.syslog_ng.LogPipe.initProxy(LogPipe.java:64)
log4j:ERROR Ignoring configuration file [file:/etc/elasticsearch/log4j2.properties].
```

If we will build it from scratch, would you know where the default location SYSLOG-NG is looking at so we can build the new log4j.properties directly in that directory.

Looking forward to your quick response.

**Comment by JawadKM** [comment]
Hi again,
I made a way head and now i am stuck here, would some one be able to assist me in resolving this issue.
Your help will be highly appreciated.

> -- Unit syslog-ng.service has begun starting up.
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f9ac80cd000, 2555904, 1) failed; error='Permission denied' (errno=13)
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: #
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: # There is insufficient memory for the Java Runtime Environment to continue.
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: # Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory.
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: # An error report file with more information is saved as:
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca syslog-ng[9542]: # /tmp/hs_err_pid9542.log
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca systemd[1]: syslog-ng.service: main process exited, code=exited, status=1/FAILURE
> Sep 20 17:01:29 opendj.dev.oneidfederation.ehealthontario.ca systemd[1]: Failed to start System Logger Daemon.
> -- Subject: Unit syslog-ng.service has failed

When I further drill down into the issue it gives me this

> [root@opendj syslog-ng]# sudo tail -f /tmp/hs_err_pid9545.log
> 
> 
> 
> Memory: 4k page, physical 8010104k(2211392k free), swap 2097148k(2097148k free)
> 
> vm_info: OpenJDK 64-Bit Server VM (25.181-b13) for linux-amd64 JRE (1.8.0_181-b13), built on Jul 23 2018 15:56:20 by "mockbuild" with gcc 4.8.5 20150623 (Red Hat 4.8.5-28)

looking forward to here from you soon.
