### ISSUE TITLE
syslog-ng dumps core on start when running on Aarch64

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2377]
# syslog-ng

## Version of syslog-ng

As even ``syslog-ng -V`` does not work:
```
[root@localhost ~]# syslog-ng -V
Segmentation fault (core dumped)
```
so I include rpm information:
```
[root@localhost ~]# rpm -qi syslog-ng
Name        : syslog-ng
Version     : 3.17.2
Release     : 1.fc29
Architecture: aarch64
Install Date: Fri 26 Oct 2018 13:13:32 CEST
Group       : System Environment/Daemons
Size        : 4424223
License     : GPLv2+
Signature   : RSA/SHA256, Sat 11 Aug 2018 09:06:24 CEST, Key ID a20aa56b429476b4
Source RPM  : syslog-ng-3.17.2-1.fc29.src.rpm
Build Date  : Sat 11 Aug 2018 09:02:58 CEST
Build Host  : buildhw-aarch64-08.arm.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://syslog-ng.org/
Bug URL     : https://bugz.fedoraproject.org/syslog-ng
Summary     : Next-generation syslog server
Description :
syslog-ng is an enhanced log daemon, supporting a wide range of input and
output methods: syslog, unstructured text, message queues, databases (SQL
and NoSQL alike) and more.

Key features:

 * receive and send RFC3164 and RFC5424 style syslog messages
 * work with any kind of unstructured data
 * receive and send JSON formatted messages
 * classify and structure logs with builtin parsers (csv-parser(),
   db-parser(), ...)
 * normalize, crunch and process logs as they flow through the system
 * hand on messages for further processing using message queues (like
   AMQP), files or databases (like PostgreSQL or MongoDB).
[root@localhost ~]# rpm -qi ivykis
Name        : ivykis
Version     : 0.42.3
Release     : 2.fc29
Architecture: aarch64
Install Date: Fri 26 Oct 2018 13:13:31 CEST
Group       : System Environment/Libraries
Size        : 104444
License     : LGPLv2+
Signature   : RSA/SHA256, Tue 24 Jul 2018 16:16:32 CEST, Key ID a20aa56b429476b4
Source RPM  : ivykis-0.42.3-2.fc29.src.rpm
Build Date  : Tue 24 Jul 2018 16:04:15 CEST
Build Host  : buildvm-aarch64-19.arm.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://libivykis.sourceforge.net/
Bug URL     : https://bugz.fedoraproject.org/ivykis
Summary     : Library for asynchronous I/O readiness notification
Description :
ivykis is a library for asynchronous I/O readiness notification.
It is a thin, portable wrapper around OS-provided mechanisms such
as epoll_create(2), kqueue(2), poll(2), poll(7d) (/dev/poll) and
port_create(3C).

ivykis was mainly designed for building high-performance network
applications, but can be used in any event-driven application that
uses poll(2)able file descriptors as its event sources.
```

## Platform

Fedora 29 Aarch64 (64bit ARM). Also tested on AMD64, but it runs there fine. 

# Issue

syslog-ng does not start at all on Fedora 29 / Aarch64. Might be an ivykis issue, that's why I included info about that as well.

## Failure

```
[root@localhost ~]# gdb -c sngcore /usr/sbin/syslog-ng
GNU gdb (GDB) Fedora 8.2-3.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/syslog-ng...Reading symbols from /usr/lib/debug/usr/sbin/syslog-ng-3.17.2-1.fc29.aarch64.debug...done.
done.
[New LWP 23244]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/syslog-ng -F -p /var/run/syslogd.pid'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000ffff8aa1b654 in pthr_atfork (child=<optimized out>, parent=<optimized out>, prepare=<optimized out>) at pthr.h:76
#2  iv_signal_init () at iv_signal.c:114
#3  0x0000ffff8adb4e6c in call_init (l=<optimized out>, argc=argc@entry=4, argv=argv@entry=0xffffd9b13778, env=0xffffd9b137a0) at dl-init.c:72
#4  0x0000ffff8adb4f70 in call_init (env=0xffffd9b137a0, argv=0xffffd9b13778, argc=4, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=0xffff8add8170, argc=4, argv=0xffffd9b13778, env=0xffffd9b137a0) at dl-init.c:119
#6  0x0000ffff8ada8104 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000ffff8aa1b654 in pthr_atfork (child=<optimized out>, parent=<optimized out>, prepare=<optimized out>) at pthr.h:76
No locals.
#2  iv_signal_init () at iv_signal.c:114
No locals.
#3  0x0000ffff8adb4e6c in call_init (l=<optimized out>, argc=argc@entry=4, argv=argv@entry=0xffffd9b13778, env=0xffffd9b137a0) at dl-init.c:72
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
        init_array = <optimized out>
#4  0x0000ffff8adb4f70 in call_init (env=0xffffd9b137a0, argv=0xffffd9b13778, argc=4, l=<optimized out>) at dl-init.c:30
        init_array = <optimized out>
        init_array = <optimized out>
        j = <optimized out>
        jm = <optimized out>
        addrs = <optimized out>
#5  _dl_init (main_map=0xffff8add8170, argc=4, argv=0xffffd9b13778, env=0xffffd9b137a0) at dl-init.c:119
        preinit_array = 0x0
        preinit_array_size = <optimized out>
        i = 8
#6  0x0000ffff8ada8104 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
        _dl_rtld_libname2 = {name = 0x0, next = 0x0, dont_free = 0}
        any_debug = 0
        cpu_list = <optimized out>
        preloadlist = 0x0
        library_path = 0x0
        version_info = 0
        audit_list = 0x0
        _dl_rtld_libname = {name = 0xaaaad370f238 "/lib/ld-linux-aarch64.so.1", next = 0xffff8add8048 <newname>, dont_free = 0}
        tls_init_tp_called = true
        __GI__dl_starting_up = 1
        _rtld_global_ro = {_dl_debug_mask = 0, _dl_osversion = 266768, _dl_platform = 0xffffd9b13928 "aarch64", _dl_platformlen = 7, _dl_pagesize = 4096, _dl_inhibit_cache = 0, _dl_initial_searchlist = {
            r_list = 0xffff8adcb6f0, r_nlist = 29}, _dl_clktck = 100, _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, _dl_dynamic_weak = 0, _dl_fpu_control = 0, _dl_correct_cache_id = 2563, 
          _dl_hwcap = 2303, _dl_auxv = 0xffffd9b137d0, _dl_aarch64_cpu_features = {midr_el1 = 1092604018, zva_size = 64}, _dl_aarch64_cap_flags = {"fp\000\000\000\000\000\000\000", "asimd\000\000\000\000", 
            "evtstrm\000\000", "aes\000\000\000\000\000\000", "pmull\000\000\000\000", "sha1\000\000\000\000\000", "sha2\000\000\000\000\000", "crc32\000\000\000\000", "atomics\000\000", 
            "fphp\000\000\000\000\000", "asimdhp\000\000", "cpuid\000\000\000\000", "asimdrdm\000", "jscvt\000\000\000\000", "fcma\000\000\000\000\000", "lrcpc\000\000\000\000", "dcpop\000\000\000\000", 
            "sha3\000\000\000\000\000", "sm3\000\000\000\000\000\000", "sm4\000\000\000\000\000\000", "asimddp\000\000", "sha512\000\000\000", "sve\000\000\000\000\000\000", "asimdfhm\000", 
            "dit\000\000\000\000\000\000", "uscat\000\000\000\000", "ilrcpc\000\000\000", "flagm\000\000\000\000"}, _dl_inhibit_rpath = 0x0, _dl_origin_path = 0x0, _dl_use_load_bias = 0, _dl_profile = 0x0, 
          _dl_profile_output = 0xffff8adbf6e0 "/var/tmp", _dl_trace_prelink = 0x0, _dl_trace_prelink_map = 0x0, _dl_init_all_dirs = 0xffff8add8c30, _dl_sysinfo_dso = 0xffff8add5000, 
          _dl_sysinfo_map = 0xffff8add8710, _dl_hwcap2 = 0, _dl_debug_printf = 0xffff8adb5bd8 <_dl_debug_printf>, _dl_mcount = 0xffff8adb6e28 <__GI__dl_mcount>, 
          _dl_lookup_symbol_x = 0xffff8adb0770 <_dl_lookup_symbol_x>, _dl_open = 0xffff8adb85f0 <_dl_open>, _dl_close = 0xffff8adba210 <_dl_close>, 
          _dl_tls_get_addr_soft = 0xffff8adb7e38 <_dl_tls_get_addr_soft>, _dl_discover_osversion = 0xffff8adbc270 <_dl_discover_osversion>, _dl_audit = 0x0, _dl_naudit = 0}
        audit_list_string = 0x0
        _dl_argc = 4
        __stack_chk_guard = 15396542223785862656
        __GI__dl_argv = 0xffffd9b13778
        _rtld_global = {_dl_ns = {{_ns_loaded = 0xffff8add8170, _ns_nloaded = 30, _ns_main_searchlist = 0xffff8add8430, _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {
                      __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 30 times>, 
--Type <RET> for more, q to quit, c to continue without paging--
                    __align = 0}}, entries = 0x0, size = 0, n_elements = 0, free = 0x0}, _ns_debug = {r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}}, {_ns_loaded = 0x0, 
              _ns_nloaded = 0, _ns_main_searchlist = 0x0, _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, 
                      __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 47 times>, __align = 0}}, entries = 0x0, size = 0, n_elements = 0, free = 0x0}, _ns_debug = {r_version = 0, 
                r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}} <repeats 15 times>}, _dl_nns = 1, _dl_load_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, 
                __kind = 1, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 30 times>, __align = 0}}, _dl_load_write_lock = {mutex = {__data = {
                __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 30 times>, 
              __align = 0}}, _dl_load_adds = 30, _dl_initfirst = 0x0, _dl_profile_map = 0x0, _dl_num_relocations = 4849, _dl_num_cache_relocations = 26, _dl_all_dirs = 0xffff8add8c30, _dl_rtld_map = {
            l_addr = 281473011314688, l_name = 0xaaaad370f238 "/lib/ld-linux-aarch64.so.1", l_ld = 0xffff8add6dc8, l_next = 0xffff8adce500, l_prev = 0xffff8adce000, l_real = 0xffff8add7a18 <_rtld_local+2584>, 
            l_ns = 0, l_libname = 0xffff8add8018 <_dl_rtld_libname>, l_info = {0x0, 0x0, 0xffff8add6e48, 0xffff8add6e38, 0xffff8add6dd8, 0xffff8add6df8, 0xffff8add6e08, 0xffff8add6e78, 0xffff8add6e88, 
              0xffff8add6e98, 0xffff8add6e18, 0xffff8add6e28, 0x0, 0x0, 0xffff8add6dc8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xffff8add6e58, 0x0, 0x0, 0xffff8add6e68, 0xffff8add6ec8, 0x0 <repeats 12 times>, 
              0xffff8add6eb8, 0xffff8add6ea8, 0xffff8add6ed8, 0x0, 0xffff8add6ef8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xffff8add6ee8, 0x0 <repeats 25 times>, 0xffff8add6de8}, l_phdr = 0xffff8ada7040, 
            l_entry = 0, l_phnum = 7, l_ldnum = 0, l_searchlist = {r_list = 0x0, r_nlist = 0}, l_symbolic_searchlist = {r_list = 0x0, r_nlist = 0}, l_loader = 0x0, l_versions = 0xffff8adc8240, l_nversions = 4, 
            l_nbuckets = 17, l_gnu_bitmask_idxbits = 3, l_gnu_shift = 8, l_gnu_bitmask = 0xffff8ada72e0, {l_gnu_buckets = 0xffff8ada7300, l_chain = 0xffff8ada7300}, {l_gnu_chain_zero = 0xffff8ada7338, 
              l_buckets = 0xffff8ada7338}, l_direct_opencount = 0, l_type = lt_library, l_relocated = 1, l_init_called = 1, l_global = 1, l_reserved = 0, l_phdr_allocated = 0, l_soname_added = 0, l_faked = 0, 
            l_need_tls_init = 0, l_auditing = 0, l_audit_any_plt = 0, l_removed = 0, l_contiguous = 0, l_symbolic_in_local_scope = 0, l_free_initfini = 0, l_rpath_dirs = {dirs = 0x0, malloced = 0}, 
            l_reloc_result = 0x0, l_versyms = 0xffff8ada7988, l_origin = 0x0, l_map_start = 281473011314688, l_map_end = 281473011515760, l_text_end = 281473011414152, l_scope_mem = {0x0, 0x0, 0x0, 0x0}, 
            l_scope_max = 0, l_scope = 0x0, l_local_scope = {0x0, 0x0}, l_file_id = {dev = 0, ino = 0}, l_runpath_dirs = {dirs = 0x0, malloced = 0}, l_initfini = 0x0, l_reldeps = 0x0, l_reldepsmax = 0, 
            l_used = 1, l_feature_1 = 0, l_flags_1 = 0, l_flags = 0, l_idx = 0, l_mach = {plt = 0, tlsdesc_table = 0x0}, l_lookup_cache = {sym = 0xffff8ada74a8, type_class = 1, value = 0xffff8adce000, 
              ret = 0xffff8a87e3d0}, l_tls_initimage = 0x0, l_tls_initimage_size = 0, l_tls_blocksize = 0, l_tls_align = 0, l_tls_firstbyte_offset = 0, l_tls_offset = 0, l_tls_modid = 0, l_tls_dtor_count = 0, 
            l_relro_addr = 194056, l_relro_size = 2552, l_serial = 0, l_audit = 0xffff8add7e88 <_rtld_local+3720>}, audit_data = {{cookie = 0, bindflags = 0} <repeats 16 times>}, 
          _dl_rtld_lock_recursive = 0xffff8a9ecdd0 <__GI___pthread_mutex_lock>, _dl_rtld_unlock_recursive = 0xffff8a9ee570 <__GI___pthread_mutex_unlock>, 
          _dl_make_stack_executable_hook = 0xffff8a9e9a70 <__make_stacks_executable>, _dl_stack_flags = 6, _dl_tls_dtv_gaps = false, _dl_tls_max_dtv_idx = 7, _dl_tls_dtv_slotinfo_list = 0xffff8adc93a0, 
          _dl_tls_static_nelem = 7, _dl_tls_static_size = 11168, _dl_tls_static_used = 9489, _dl_tls_static_align = 16, _dl_initial_dtv = 0xffff8a0cb2d0, _dl_tls_generation = 1, 
          _dl_init_static_tls = 0xffff8a9ea0d0 <__pthread_init_static_tls>, _dl_wait_lookup_done = 0xffff8a9ea200 <__wait_lookup_done>, _dl_scope_free_list = 0x0}
        _dl_skip_args = 0
        __pointer_chk_guard_local = 17674652238786345737
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

```

## Steps to reproduce

1. start syslog-ng

**Comment by furiel** [comment]
@czanik please subscribe for https://github.com/buytenh/ivykis/issues/15

**Comment by Kokan** [comment]
This is - as @furiel pointed out - a duplicated ticket, so I am closing this one: https://github.com/balabit/syslog-ng/issues/2263

**Comment by czanik** [comment]
Fixed by a rebuild of ivykis for Fedora 29 Aarch64: https://bodhi.fedoraproject.org/updates/FEDORA-2018-d3f52c78c4
