### ISSUE TITLE
Unable to change and search my Index name using syslog-ng

### ISSUE THREAD

**Issue by JawadKM** [balabit/syslog-ng#2420]
Hi syslog-ng Team,
I am using Syslog-ng to push logs to Elasticsearch and then view in Kibana on CentOs7, using the following link;

**https://www.syslog-ng.com/community/b/blog/posts/syslog-ng-and-elasticsearch-6-getting-started-on-rhelcentos**

In my lab environment when I change my cluster name from syslog-ng to **"Lab"** and change my Index name to **"labtest"**. Kibana never recognize it and keeps me giving **"syslog-ng"** as the only Index available.

**Second** issue is that in elasticsearch.yml file if I configure the cluster.name as;

echo cluster.name: syslog-ng >> /etc/elasticsearch/elasticsearch.yml

as given in the instructions it gives me an error, shown below;

[root@opendj elasticsearch]# systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-11-19 16:58:43 UTC; 1s ago
     Docs: http://www.elastic.co
  Process: 2458 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 2458 (code=exited, status=1/FAILURE)

Nov 19 16:58:25 opendj.lab.oneidfederation.ehealthontario.ca systemd[1]: Started Elasticsearch.
Nov 19 16:58:25 opendj.lab.oneidfederation.ehealthontario.ca systemd[1]: Starting Elasticsearch...
Nov 19 16:58:27 opendj.lab.oneidfederation.ehealthontario.ca elasticsearch[2458]: OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of par...elGCThreads=N
Nov 19 16:58:43 opendj.lab.oneidfederation.ehealthontario.ca systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Nov 19 16:58:43 opendj.lab.oneidfederation.ehealthontario.ca systemd[1]: Unit elasticsearch.service entered failed state.
Nov 19 16:58:43 opendj.lab.oneidfederation.ehealthontario.ca systemd[1]: elasticsearch.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**[root@opendj elasticsearch]# /usr/share/elasticsearch/bin/elasticsearch**
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[2018-11-19T16:59:26,441][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:104) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:171) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.0.jar:6.4.0]
        ... 6 more

And if I remove **echo** from the cluster.name statement it starts working again.

Please help me in resolving this issue, your help will me much appriciated as I have to make my system run asap.

Looking forward to hearing from you soon.

**Comment by lbudai** [comment]
@JawadKM: hi! without analyzing the attached trace: did you also modify the `index` option in your _syslog-ng.conf_ ?

**Comment by JawadKM** [comment]
@lbudai Yes I did, could it be because there are no logs generated at the moment and no documents are in the index.

**Comment by szemere** [comment]
Hello,
> could it be because there are no logs generated at the moment and no documents are in the index.

Yes.
In my 3 week old comment https://github.com/balabit/syslog-ng/issues/2349#issuecomment-431035342 (can we close it?) I used dejavu as a GUI. You did not mentioned your interface, but empty indexes are usually not presented.
Just generate some logs to test it.


The **first** line of the attached trace says: `can not run elasticsearch as root`

One more thing:
`echo cluster.name: syslog-ng >> /etc/elasticsearch/elasticsearch.yml`
Do you apply this command to an empty config? Or simply append it to the end of a previous one? I guess you can not put one node into two different cluster at the same time. (I can not find anything in the docs, testing is in progress.)

**Comment by JawadKM** [comment]
@szemere 
Yes I am applying it to an empty config.
yes you can close #2349

**Comment by szemere** [comment]
Dear @JawadKM ,
 can I help you anymore in the topic, or should I close this ticket?

Br,
Laci
