### ISSUE TITLE
when log threaded dest driver not available, on SIGTERM syslog-ng segfaults

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#395]
reproduction:
1, start syslog-ng with the following config:
```
@version: 3.7
source s_net{
        tcp( port(3333) );
    };
destination d_amqp {
        amqp(
            vhost("/")
#            host("127.0.0.1")
            host("1.1.1.1")
            port(5672)
            exchange("syslog")
            exchange_type("header")
            routing_key("")
            body("")
            persistent(yes)
            username("guest")
            password("guest")
            value-pairs(
                scope("selected-macros" "nv-pairs" "sdata")
            )
        );
    };
log{
    source(s_net);
    destination(d_amqp);
};
```
2, send stop signal to syslog-ng, syslog-ng will crash

the backtrace:
```
Core was generated by `sbin/syslog-ng -Fedvt -f /home/micek/micek-home-dir/work/syslog-ng-confs/syslog'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=0x7f08533773d0) at ../nptl/pthread_mutex_lock.c:66
66	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt full
#0  __GI___pthread_mutex_lock (mutex=0x7f08533773d0) at ../nptl/pthread_mutex_lock.c:66
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = 16745456
#1  0x00007f0852f2ed3e in mutex_lock (mutex=0xa0) at ../../../../lib/ivykis/src/mutex.h:38
No locals.
#2  iv_event_post (this=0xff83f0) at ../../../../lib/ivykis/src/iv_event.c:163
        tinfo = 0x0
        post = 0
#3  0x00007f0852eebf22 in log_threaded_dest_driver_stop_thread (s=0xff8290) at ../lib/logthrdestdrv.c:259
        self = 0xff8290
#4  0x00007f0852ef1226 in _invoke_worker_exit_callback (func=0xfdb7b0) at ../lib/mainloop-worker.c:142
No locals.
#5  0x00007f0852be5648 in g_list_foreach () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007f0852ef1247 in _request_all_threads_to_exit () at ../lib/mainloop-worker.c:148
No locals.
#7  0x00007f0852ef168b in main_loop_worker_sync_call (func=0x7f0852ef0393 <main_loop_exit_finish>) at ../lib/mainloop-worker.c:341
        __func__ = "main_loop_worker_sync_call"
#8  0x00007f0852ef03c5 in main_loop_exit_timer_elapsed (arg=0x0) at ../lib/mainloop.c:304
No locals.
#9  0x00007f0852f2f67a in iv_run_timers (st=st@entry=0xfcc740) at ../../../../lib/ivykis/src/iv_timer.c:149
        t = 0x7f0853174700 <main_loop_exit_timer>
#10 0x00007f0852f31184 in iv_main () at ../../../../lib/ivykis/src/iv_main_posix.c:107
        to = {tv_sec = 0, tv_nsec = 100000000}
#11 0x00007f0852ef0848 in main_loop_run () at ../lib/mainloop.c:502
No locals.
#12 0x0000000000401abb in main (argc=1, argv=0x7fff717988e8) at ../syslog-ng/main.c:270
        rc = 0
        ctx = 0xfcb970
        error = 0x0
(gdb) fr 3
#3  0x00007f0852eebf22 in log_threaded_dest_driver_stop_thread (s=0xff8290) at ../lib/logthrdestdrv.c:259
259	  iv_event_post(&self->shutdown_event);
(gdb) p *(self)
$1 = {super = {super = {super = {ref_cnt = {counter = 2}, flags = 3, cfg = 0xfd8e20, expr_node = 0xffbe80, pipe_next = 0xfd3210, queue_data = 0x0, queue = 0x7f0852eec360 <log_threaded_dest_driver_queue>, 
        init = 0x7f08504b03a1 <afamqp_dd_init>, deinit = 0x7f0852eec1d0 <log_threaded_dest_driver_deinit_method>, clone = 0x0, free_fn = 0x7f08504b0554 <afamqp_dd_free>, notify = 0x0}, optional = 0, group = 0xfda8c0 "d_amqp", 
      id = 0xfda970 "d_amqp#0", plugins = 0x0, processed_group_messages = 0xfda604}, acquire_queue_data = 0x0, acquire_queue = 0x7f0852edc53c <log_dest_driver_acquire_queue_method>, release_queue_data = 0x0, 
    release_queue = 0x7f0852edc60c <log_dest_driver_release_queue_method>, queues = 0xff73a0, log_fifo_size = -1, throttle = 0, queued_global_messages = 0xfdb554}, dropped_messages = 0xfdb820, stored_messages = 0xfdb828, suspended = 0, 
  time_reopen = 60, queue = 0xfdb870, worker = {thread_init = 0x7f08504b037a <afamqp_worker_thread_init>, thread_deinit = 0x0, insert = 0x7f08504b0321 <afamqp_worker_insert>, disconnect = 0x7f08504af55c <afamqp_dd_disconnect>}, 
  messages = {retry_over = 0x0}, format = {stats_instance = 0x7f08504af458 <afamqp_dd_format_stats_instance>, persist_name = 0x7f08504af4da <afamqp_dd_format_persist_name>}, stats_source = 29, seq_num = 1, retries = {counter = 0, 
    max = 3}, queue_method = 0x0, worker_options = {is_output_thread = 1}, wake_up_event = {cookie = 0x0, handler = 0x0, tinfo = 0x0, list = {next = 0x0, prev = 0x0}}, shutdown_event = {cookie = 0x0, handler = 0x0, tinfo = 0x0, list = {
      next = 0x0, prev = 0x0}}, timer_reopen = {expires = {tv_sec = 0, tv_nsec = 0}, cookie = 0x0, handler = 0x0, pad = {0x0, 0x0, 0x0, 0x0}}, timer_throttle = {expires = {tv_sec = 0, tv_nsec = 0}, cookie = 0x0, handler = 0x0, pad = {
      0x0, 0x0, 0x0, 0x0}}, do_work = {cookie = 0x0, handler = 0x0, pad = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}}

```

syslog-ng version:

syslog-ng 3.7.0alpha2
Installer-Version: 3.7.0alpha2
Revision: 
Compile-Date: Feb 23 2015 13:52:48
Available-Modules: mod-python,csvparser,afamqp,afuser,afprog,confgen,afsql,afsocket,pseudofile,redis,affile,basicfuncs,syslogformat,cryptofuncs,json-plugin,afstomp,linux-kmsg-format,dbparser,system-source,afmongodb,riemann,afsmtp,tfgeoip,graphite,sdjournal
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

**Comment by mitzkia** [comment]
With the current master is: 1e9a30127ad2c9e90155139eb87c5ffb20ba436a, 
which already contains:
#399 
#393 
Reproduced the bug with the above steps syslog-ng crashes in other place, the new backtrace is:
```
Core was generated by `sbin/syslog-ng -Fedv -f syslog-ng.conf --enable-core'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fe06da90cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007fe06da90cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 30570
        selftid = 30571
#1  0x00007fe06da940d8 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fff6a8205d2, sa_sigaction = 0x7fff6a8205d2}, sa_mask = {__val = {140601890532636, 140601854362176, 206, 4294967295, 140601889174755, 4294967296, 140601903339472, 474251272944, 
              26321040, 0, 0, 0, 0, 21474836480, 140601903439872, 140601890547760}}, sa_flags = 1804960625, sa_restorer = 0x7fe06b958570 <__PRETTY_FUNCTION__.7177>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fe06da89b86 in __assert_fail_base (fmt=0x7fe06dbda830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fe06b958371 "self", 
    file=file@entry=0x7fe06b958240 "../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c", line=line@entry=206, function=function@entry=0x7fe06b958570 <__PRETTY_FUNCTION__.7177> "amqp_socket_send") at assert.c:92
        str = 0x7fe064013e10 "syslog-ng: ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c:206: amqp_socket_send: Assertion `self' failed.\n"
        total = 4096
#3  0x00007fe06da89c32 in __GI___assert_fail (assertion=assertion@entry=0x7fe06b958371 "self", file=file@entry=0x7fe06b958240 "../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c", line=line@entry=206, 
    function=function@entry=0x7fe06b958570 <__PRETTY_FUNCTION__.7177> "amqp_socket_send") at assert.c:101
No locals.
#4  0x00007fe06b95052a in amqp_socket_send (self=<optimized out>, buf=<optimized out>, len=<optimized out>) at ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c:206
        __PRETTY_FUNCTION__ = "amqp_socket_send"
#5  0x00007fe06b94be82 in amqp_send_frame (state=state@entry=0x7fe064003a00, frame=frame@entry=0x7fe06e80d990) at ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_connection.c:527
        out_frame_len = <optimized out>
        out_frame = 0x7fe064003b90
        res = <optimized out>
#6  0x00007fe06b9514ee in amqp_send_method (state=state@entry=0x7fe064003a00, channel=channel@entry=1, id=id@entry=1310760, decoded=decoded@entry=0x7fe06e80da80) at ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c:961
        frame = {frame_type = 1 '\001', channel = 1, payload = {method = {id = 1310760, decoded = 0x7fe06e80da80}, properties = {class_id = 40, body_size = 140601903340160, decoded = 0x7fe06e80da70, raw = {len = 140601903340160, 
                bytes = 0x191a090}}, body_fragment = {len = 1310760, bytes = 0x7fe06e80da80}, protocol_header = {transport_high = 40 '(', transport_low = 0 '\000', protocol_version_major = 20 '\024', protocol_version_minor = 0 '\000'}}}
#7  0x00007fe06b951557 in amqp_simple_rpc (state=state@entry=0x7fe064003a00, channel=channel@entry=1, request_id=request_id@entry=1310760, expected_reply_ids=expected_reply_ids@entry=0x7fe06e80da70, 
    decoded_request_method=decoded_request_method@entry=0x7fe06e80da80) at ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_socket.c:986
        status = <optimized out>
        result = {reply_type = AMQP_RESPONSE_NONE, reply = {id = 0, decoded = 0x0}, library_error = 0}
#8  0x00007fe06b94b459 in amqp_channel_close (state=0x7fe064003a00, channel=<optimized out>, code=<optimized out>) at ../../../../modules/afamqp/rabbitmq-c/librabbitmq/amqp_api.c:271
        codestr = "200\000\000\000\000\000\000:\000", <incomplete sequence \340>
        replies = {1310761, 0}
        req = {reply_code = 200, reply_text = {len = 3, bytes = 0x7fe06e80daa0}, class_id = 0, method_id = 0}
#9  0x00007fe06b949d51 in afamqp_dd_disconnect (s=0x191a6d0) at ../modules/afamqp/afamqp.c:223
        self = 0x191a6d0
#10 0x00007fe06e389139 in log_threaded_dest_driver_worker_thread_main (arg=0x191a6d0) at ../lib/logthrdestdrv.c:245
        self = 0x191a6d0
#11 0x00007fe06e38e767 in _worker_thread_func (st=0x1920100) at ../lib/mainloop-worker.c:280
---Type <return> to continue, or q <return> to quit---
        p = 0x1920100
        __func__ = "_worker_thread_func"
#12 0x00007fe06e0aaf05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x00007fe06de27182 in start_thread (arg=0x7fe06e810700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fe06e810700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140601903351552, -7948903820790509966, 0, 0, 140601903352256, 140601903351552, 7957595656557252210, 7957589872499445362}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#14 0x00007fe06db5447d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
