### ISSUE TITLE
Segfault when reading journald log files

### ISSUE THREAD

**Issue by Gu1** [balabit/syslog-ng#459]
On my Arch system, syslog-ng segfaults when starting.
Here is the backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde96b700 (LWP 9583)]
0x00007ffff485037e in __handle_data (key=0x0, value=0x7fffd00032a0 "_MACHINE_IDXXXXX", user_data=<optimized out>) at modules/systemd-journal/journal-reader.c:161
161	  if (strcmp(key, "MESSAGE") == 0)
(gdb) bt
#0  0x00007ffff485037e in __handle_data (key=0x0, value=0x7fffd00032a0 "_MACHINE_IDXXXXX", user_data=<optimized out>)
    at modules/systemd-journal/journal-reader.c:161
#1  0x00007ffff4851537 in journald_foreach_data (self=0x69e230, func=func@entry=0x7ffff4850330 <__handle_data>, user_data=user_data@entry=0x7fffde968960)
    at modules/systemd-journal/journald-helper.c:58
#2  0x00007ffff4850c69 in __handle_message (self=0x6151f0) at modules/systemd-journal/journal-reader.c:237
#3  __fetch_log (self=self@entry=0x6151f0) at modules/systemd-journal/journal-reader.c:360
#4  0x00007ffff48510a9 in __work_perform (s=0x6151f0) at modules/systemd-journal/journal-reader.c:404
#5  0x00007ffff7b7605d in _work (self=<optimized out>) at lib/mainloop-io-worker.c:52
#6  0x00007ffff7b9d977 in iv_work_thread_do_work (_thr=0x61e6b0) at iv_work.c:118
#7  0x00007ffff7b9cc43 in iv_run_tasks (st=st@entry=0x7fffd00008c0) at iv_task.c:48
#8  0x00007ffff7b9ef8c in iv_main () at iv_main_posix.c:106
#9  0x00007ffff7b9d7c4 in iv_work_thread (_thr=0x61e6b0) at iv_work.c:200
#10 0x00007ffff7b9f7f8 in iv_thread_handler (_thr=0x61e780) at iv_thread_posix.c:142
#11 0x in start_thread () from /usr/lib/libpthread.so.0
#12 0x in clone () from /usr/lib/libc.so.6
```

This seems to happen because journald_foreach_data can pass a NULL key to the callback when there is no "=" in the message, but __handle_data() in journal-reader.c doesn't check for it.
I've ran journalctl --verify and my log isn't corrupted.

**Comment by dnsjts** [comment]
I am trying to reproduce the issue.
Could you upload the syslog-ng configuration in the meantime?

**Comment by algernon** [comment]
Not sure how one can end up with a journal data value without `=`. My attempts at constructing such a message failed so far. Nevertheless, that case should be handled gracefully by syslog-ng nevertheless.

**Comment by Gu1** [comment]
The only custom journald configuration I have is ForwardToSyslog=yes:
```
[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitInterval=30s
#RateLimitBurst=1000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#MaxRetentionSec=
#MaxFileSec=1month
ForwardToSyslog=yes
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

As for syslog-ng, I also use the default configuration provided by archlinux, the only difference I see is the /proc/kmsg source :

```
@version: 3.6
@include "scl.conf"
#
# /etc/syslog-ng/syslog-ng.conf
#

options {
  stats_freq (0);
  flush_lines (0);
  time_reopen (10);
  log_fifo_size (10000);
  chain_hostnames (off);
  use_dns (no);
  use_fqdn (no);
  create_dirs (no);
  keep_hostname (yes);
  perm(0640);
  group("log");
};

source src {
  system();
  internal();
  file("/proc/kmsg");
};

destination d_authlog { file("/var/log/auth.log"); };
destination d_syslog { file("/var/log/syslog.log"); };
destination d_cron { file("/var/log/crond.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kernel { file("/var/log/kernel.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_news { file("/var/log/news.log"); };
destination d_ppp { file("/var/log/ppp.log"); };
destination d_debug { file("/var/log/debug.log"); };
destination d_messages { file("/var/log/messages.log"); };
destination d_errors { file("/var/log/errors.log"); };
destination d_everything { file("/var/log/everything.log"); };
destination d_iptables { file("/var/log/iptables.log"); };
destination d_acpid { file("/var/log/acpid.log"); };
destination d_console { usertty("root"); };

# Log everything to tty12
destination console_all { file("/dev/tty12"); };

filter f_auth { facility(auth); };
filter f_authpriv { facility(auth, authpriv); };
filter f_syslog { program(syslog-ng); };
filter f_cron { facility(cron); };
filter f_daemon { facility(daemon); };
filter f_kernel { facility(kern) and not filter(f_iptables); };
filter f_lpr { facility(lpr); };
filter f_mail { facility(mail); };
filter f_news { facility(news); };
filter f_user { facility(user); };
filter f_uucp { facility(uucp); };
filter f_ppp { facility(local2); };
filter f_debug { not facility(auth, authpriv, news, mail); };
filter f_messages { level(info..warn) and not facility(auth, authpriv, mail, news, cron) and not program(syslog-ng) and not filter(f_iptables); };
filter f_everything { level(debug..emerg) and not facility(auth, authpriv); };
filter f_emergency { level(emerg); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_crit { level(crit); };
filter f_err { level(err); };
filter f_iptables { match("IN=" value("MESSAGE")) and match("OUT=" value("MESSAGE")); };
filter f_acpid { program("acpid"); };

log { source(src); filter(f_acpid); destination(d_acpid); };
log { source(src); filter(f_authpriv); destination(d_authlog); };
log { source(src); filter(f_syslog); destination(d_syslog); };
log { source(src); filter(f_cron); destination(d_cron); };
log { source(src); filter(f_daemon); destination(d_daemon); };
log { source(src); filter(f_kernel); destination(d_kernel); };
log { source(src); filter(f_lpr); destination(d_lpr); };
log { source(src); filter(f_mail); destination(d_mail); };
log { source(src); filter(f_news); destination(d_news); };
log { source(src); filter(f_ppp); destination(d_ppp); };
log { source(src); filter(f_user); destination(d_user); };
log { source(src); filter(f_uucp); destination(d_uucp); };
#log { source(src); filter(f_debug); destination(d_debug); };
log { source(src); filter(f_messages); destination(d_messages); };
log { source(src); filter(f_err); destination(d_errors); };
log { source(src); filter(f_emergency); destination(d_console); };
log { source(src); filter(f_everything); destination(d_everything); };
log { source(src); filter(f_iptables); destination(d_iptables); };

# Log everything to tty12
#log { source(src); destination(console_all); };
```

**Comment by Gu1** [comment]
Any update on this ?

**Comment by bazsi** [comment]
I have opened a pull request in parallel, PR #462, ops, should have checked first :)

anyway, I like my solution a bit more, as we drop the value earlier, not passing invalid data to the foreach function, but please feel free to merge any of the two fixes.

Cheers,
Bazsi

**Comment by juhaszviktor** [comment]
+1
@Bazsi: I think your PR is better, than mine :)

BR,
Viktor

**Comment by ihrwein** [comment]
Bazsi's solution, https://github.com/balabit/syslog-ng/pull/462 is merged. Do you wish to verify it? Otherwise we may close this issue.

**Comment by Gu1** [comment]
I think you can close it. I'll create another one if there are other problems or crashes.

**Comment by ihrwein** [comment]
Ok, thanks!
